### ISSUE TITLE
Problem Changing Keyboard command in ProjectionMappingState.cp

### ISSUE THREAD

**Issue by navlisilvan** [magdesign/PocketVJ-CP-v3#1]
Hello,

i am not able to change OF_KEY_BACKSPACE in 'd', than the make will stop with an arror, because there is already an 'd' - case.
and another problem:
] to v
[ to b
{ to m
} to m

maybe you wanted to say:
] to v
[ to b
{ to n
} to m

or?
Thanks a lot!

**Comment by magdesign** [comment]
thanks for the info.
kr15h made some upgrades with minor changes in the keyboard shortcuts.

since 'd' is also used in older version of PocketVJ I like to keep it for "delete surface".

So I upgraded the readme with the new changes.
