### ISSUE TITLE
Unable to locate package mountusb

### ISSUE THREAD

**Issue by pietrondo** [magdesign/PocketVJ-CP-v3#10]
Hi.
I'm making a new machine, but when I try to apt-get:

> E: Unable to locate package mountusb

which package I need to download?

thx

**Comment by magdesign** [comment]
its not an essential package, it just automounts a plugged in usb stick.

**Comment by magdesign** [comment]
try : 
apt-get install usbmount 
instead

**Comment by pietrondo** [comment]
ok thx
