### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by GreenLunar** [magdesign/PocketVJ-CP-v3#105]
Add RSS feed to your website please https://pocketvj.com/feed

You can add your Mastodon RSS feed

```
<link rel="alternate" type="application/rss+xml" title="PocketVJ" href="https://fosstodon.org/@pocketvj.rss">
```

See also https://www.rssboard.org/rss-autodiscovery

**Comment by magdesign** [comment]
there is no need since the project is on halt...

**Comment by GreenLunar** [comment]
I beg your pardon, but I disagree.

RSS is perfect for all cases, and is mostly useful for projects that
update rarely.

Please.

**Comment by GreenLunar** [comment]
On Mon, 25 Sep 2023 06:23:53 -0700
magdesign ***@***.***> wrote:

> there is no need since the project is on halt...
>

Here is an argument to convince you to add RSS.

I'm a person who likes modularity, for reasons of preservation and
utilization for a long term.

I'm also a person who like Mini-PCs and Pocket-PCs of the typeof
Pandora, DragonBox, Pyra Handhelds.

While Pyra was in its first stages, I could follow its updates via its
RSS feeds, so it was available in my RSS Reader.

On the contrary, Project POCKIT <pockit.ai> has no RSS feed, not even
of a microblog website as you have, so it went only in my bookmarks
database which counts over 7M, and the results for providers of
SBCs (store:sbc) is over 200 and Pocket-PCs (store:pocket-pc) is over
500.

For three days, I didn't find POCKIT , which was tagged under
store:computer and store:pda, up until today, when a friend from an
XMPP groupchat has accidentally found a website with a landpage that
matched my description.  The commercial search engines and ML bot
couldn't find it, even after querying that lame bot for over 50 times
in 50 fashions.

Please add an RSS feed for the sake of the project and for the sake of
those who have some interest in it.

I also suggest you to create a page for your product at postmarketOS,
even if it is entirely based on RPi or whatever SBC, so that it would
be easier to reach you, be it a person who's using pmOS or a business
person.

https://wiki.postmarketos.org/wiki/PocketVJ_(CP-v3)

**Comment by magdesign** [comment]
i will look into this.
need to figure out how to create rss feed (bootstrapstudio) and then i will add, keep in mind i am cycling and take limited screen time :)

but postmarketos wiki, i dont know why, i will add something to my userpage there..

**Comment by GreenLunar** [comment]
You already have an RSS feed.

Please look at the code provided above which links to the RSS feed of
your Mastodon account.
