### ISSUE TITLE
Unable to download working rtc image from website "about" page

### ISSUE THREAD

**Issue by BjarneJensen** [magdesign/PocketVJ-CP-v3#107]
Hope all is well. I read that you're touring the countryside on bike and that the project is on hold. Hope the fresh air and exercise are treating you well!

I had some trouble downloading the rtc image from the about page. Tried multiple times but failed. If I click “resume download” enough times, I end up with a 611 mb file which seems small to me. When flashed, I get “kernel panic no working unit found”

Any chance this will be fixed in the future or is it just an artifact of my bad download? My internet speed seems fine. Thanks

**Comment by magdesign** [comment]
see here:
https://gist.github.com/baydam/a905e4878f54150f7da421e2c1d17a21?permalink_comment_id=4700205#gistcomment-4700205

this should be fixed,
size is something around 4gb.
