### ISSUE TITLE
Develop serial port control

### ISSUE THREAD

**Issue by nuphunk** [magdesign/PocketVJ-CP-v3#11]
Hello Pocket People!

I would love to have a serial command set that replicates the current TCP set so i can control the pocketVJ via serial rs232 link.

i am using these adaptors
http://www.ebay.co.uk/itm/262761728832?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT

I am not a programmer, so i am out of my depth, but i do know how to create the drivers for the devices i want to control. Just need to establish what protocol and commands the PocketVJ should expect.

Are there any Serial geniuses who could help me with this?

Many thanks,
Nuphunk

**Comment by magdesign** [comment]
I guess you managed to connect and initialise the serial port on the RPi side.
How do the serial commands which you send to the PocketVJ look like?

All you have to do is to link each command to the relevant script located in /var/www/sync/

For example you could make a simple python script which loads at boot and listens to the serial port.
To start the script at boot, edit /var/www/sync/rc.local.custom  and then in CP set "Autostart" to custom.

**Comment by nuphunk** [comment]
Thanks for the reply. I am still trying to work out some issues with stability of the GPIO serial port (/dev/ttyS0) implementation. These are best described [here](http://spellfoundry.com/2016/05/29/configuring-gpio-serial-port-raspbian-jessie-including-pi-3/).

**Comment by magdesign** [comment]
is this still an issue ?
