### ISSUE TITLE
Mapping not possible after update

### ISSUE THREAD

**Issue by Prepete** [magdesign/PocketVJ-CP-v3#13]
Hi there, 
my pocketvj is not working any more. After having updated it the commands I can choose from the control panel (vers. 1.13) don't work no more.
Can you tell me how to fix it?
Best regards,
Peter

**Comment by magdesign** [comment]
What is not working anymore ?
Can you display a testscreen ?
Can you read out the resolution ?

If just mapper is not working, stop everything, go to system, click update mapper and wait 5 minutes.

**Comment by Prepete** [comment]
updating again and waiting for 5 min solved the problem.
