### ISSUE TITLE
integrated HPlayer-OSC 

### ISSUE THREAD

**Issue by Prepete** [magdesign/PocketVJ-CP-v3#14]
Dear Mag,
i'm trying to make use of the new integrated HPlayerOSC to switch through several videos (playlist) over the network and with an IR-remote. Now I got the problem that I can't find the tool on the device. Can you tell me how to reach it and how to use it with pocketvj? Auto starting "HPlayerOSC" doesn't show anything. There's nothing described in the manual and the description online does not work.
Best greetings from germany and thanks for your fantastic tool!
Pete

**Comment by magdesign** [comment]
Hi
Make sure you have a PocketVJ 3.3 or newer, otherwise there is no HPlayer installed. Of course you can clone it yourself from github to /home/pi/HPlayer/ 
https://github.com/Hemisphere-Project/HPlayer

**Comment by magdesign** [comment]
The manual is updated.

**Comment by Prepete** [comment]
Hi there,
I compiled an installed HPlayer like described here: https://gist.github.com/Maigre/1a7f159a81b9f1f96eb1e1d40194ad7f
Autostart works out fine but starting it manually from ~/HPlayer does not work.

**Comment by magdesign** [comment]
Sound weird to me, since both commands execute exact the same script.
Maybe making an update helps...

**Comment by Prepete** [comment]
Everything works out fine right now... reinstalled everything and configured correctly.
Thanks!!
