### ISSUE TITLE
Skip to next clip

### ISSUE THREAD

**Issue by Prepete** [magdesign/PocketVJ-CP-v3#16]
Hi there,
I wondered if it's possible to use the "normal" player function with a playlist/directory. You implemented the "fast forward - button" maybe it's possible to get an similar option to skip to the next clip?! It would be great if this function could be triggered through TCP.

**Comment by magdesign** [comment]
This is a good idea. 
I put it onto the roadmap. 
There needs to be some code in omxplayer-sync script to make this possible, since omxplayers dbuscontrol does not support playlists.  
Contributions are welcome. :-)
