### ISSUE TITLE
curser visible after having stopped the player

### ISSUE THREAD

**Issue by Prepete** [magdesign/PocketVJ-CP-v3#17]
Hi there,
I found a small bug: when using the "stop" button the courser is visible again.
Best regards,
Peter

**Comment by magdesign** [comment]
Its fixed!

Update CP 
(did not make release letter for this one, number release coming very soon)

**Comment by magdesign** [comment]
Sorry
The fix only works when executed from command line.... there are still some user issues, trying to track down the problem

**Comment by magdesign** [comment]
now it works!
