### ISSUE TITLE
Can't get time set properly

### ISSUE THREAD

**Issue by UnlimitedVideoStaging** [magdesign/PocketVJ-CP-v3#19]
Hi there,

I am planning on using our pocketVJ 3.3 in a semi-permanent install, so i'll be needing the scheduling functionality. However, after configuring the timezone using raspi-config, I still get the wrong time. 

Currently when I click on "show actual date" in the CP, it gives me a time which is behind by about 22 hours and 5 minutes.

I have restarted the pi a number of times, it is connected to the internet via ethernet and i've even tried restarting the network time protocol with :

sudo /etc/init.d/ntp stop
sudo /etc/init.d/ntp start

Any thoughts on how I might force it to update to the proper time?

Thank you,

  Sean

**Comment by magdesign** [comment]
Do you have a comptible RTC module installed on your Rpi3 ?

If yes, connect to internet, check with the date command the actual date and then write it to the module with "hwclock -w"

**Comment by magdesign** [comment]
Since the PVJ has a fixed Ip, you maybe dont get internet access on the network you are connected. 
 To fix this, switch the PVJ network to DHCP and reboot or cofigure your router to: 192.168.2.1

**Comment by UnlimitedVideoStaging** [comment]
I switched the PVJ to DHCP, rebooted and the time displays perfectly now.

Thank you so much!
