### ISSUE TITLE
How to change slideshow timing settings?

### ISSUE THREAD

**Issue by UnlimitedVideoStaging** [magdesign/PocketVJ-CP-v3#21]
Hi again, I need to change the duration of the slideshow to be much longer than the given options of 5,10 or 15 seconds. Is there a config file somewhere, that i can modify to allow a custom duration?

Thank you so much,

  Sean

**Comment by magdesign** [comment]
To change the slide show time, go to:

`/var/www/sync/xsessionslideshow`
and change the `DELAY=` value

**Comment by UnlimitedVideoStaging** [comment]
Awesome! Thanks again.
