### ISSUE TITLE
CP 1.4 Update

### ISSUE THREAD

**Issue by nuphunk** [magdesign/PocketVJ-CP-v3#22]
Hi there,

After updating to CP 1.4 i now get two lines of code before playing loops. They disappear once the clip starts unless there is no medial linked to the button, in which case the lines stay on screen.

[  OK  ] Stopped User Manager for UID 1000
[  OK  ] Removed Slice user-1000.slice.

Thanks

**Comment by magdesign** [comment]
This looks more like an ownership issue, regular user is ID 1000.
You can try with a factory preset or with a chown command.

Since you are running custom scripts I'm guessing its something to do with them.
Or is anyone else having this issue?

**Comment by magdesign** [comment]
This still persists... 
Maybe I have to add -b to all startvideo commands
