### ISSUE TITLE
Player_OSC issue on CP 1.14

### ISSUE THREAD

**Issue by dazzacurdan** [magdesign/PocketVJ-CP-v3#26]
Hi all,

from web UI i tried to enable HPlayer_OSC from Video Control tab.
The results is that videos starts in loop with decoding error (green artefact) and without audio.

More over regarding port is 9000 (default in HPlayer)?

The OSC command syntax is for Eg: /play /media/internal/video or /play [/media/internal/video]

Can you provide more details and some example on how to use osc coupled with pocket-vj?

Thank you in advance 
Paolo

**Comment by magdesign** [comment]
OSC is a pretty new materia for me, but i will make a tutorial in the next few days.  Until then you might find some answers in the PVJ manual or here: https://github.com/Hemisphere-Project/HPlayer/blob/master/README.md

**Comment by dazzacurdan** [comment]
Hi magdesign,
if you whant i can share my Processing patch that is able to interact with pocket-VJ with a small tutorial. The main issues are the decoding error and the absence of sound.

**Comment by dazzacurdan** [comment]
Hi all,

this is my test code for osc using Processing.

/**
 * pocket_vj_osc by paolo pasteris
 * example shows how to send osc message from processing to pocket-vj using keyboard.
 * oscP5 website at http://www.sojamo.de/oscP5
 */
 
import oscP5.*;
import netP5.*;

OscP5 oscP5;
NetAddress myRemoteLocation;
OscMessage play;
String path;

void setup() {
  size(400,400);
  frameRate(25);
  /* start oscP5, listening for incoming messages at port 12000 */
  oscP5 = new OscP5(this,12000);
  
  /* set the raspberry ip and the default port 9000
   */
  myRemoteLocation = new NetAddress("2.0.0.100",9000);
  
  play = new OscMessage("/play");//this is one of the available command
  path = "/media/internal/Rovello3/";//the path where the video file are collected
}


void draw() {
  background(0);  
}
/*
this callback trigger keyboard press I have simple mapped a key value with a related string
*/
void keyPressed() {
  switch(key)
  {
    case 'q':
      play.add(path+"00.mp4");
    break;
    case 'w':
      play.add(path+"01.mp4");
    break;
    case 'e':
      play.add(path+"02.mp4");
    break;
    case 'r':
      play.add(path+"03.mp4");
    break;
    case 't':
      play.add(path+"04.mp4");
    break;
    case 'y':
      play.add(path+"05.mp4");
    break;
  }
  oscP5.send(play, myRemoteLocation);
  play.print();//this command is for debug the final string
  play.clearArguments();//this command achieve to instance the message play only during the setup stage and change content using .add at runtime
}

all works correctly except audio and some video decoding issue in green

Paolo

**Comment by magdesign** [comment]
Thanks for sharing your script.
Will try as soon as I'll find some time.

About the green artefact. Are you sure its not an error from your decoder. For example if you decode in 1600x1200 on mpegstreamclip I get these artefacts. Did you try with the provided testmovies?

**Comment by dazzacurdan** [comment]
Using Play_01_loop no decoding/hw issue only using OSC messages.
I will trying with sample videos.

Paolo

**Comment by magdesign** [comment]
since today the whole CP is OSC controllable.
:-)
