### ISSUE TITLE
smb share image/video folders

### ISSUE THREAD

**Issue by SkippyDoe** [magdesign/PocketVJ-CP-v3#27]
How does one share the image and video folders so they can be accessed within Windows or Mac?
Is this possible?
PocketVJ is living in a hard to reach area.
Need to be able to dump images into the folders via windows explorer or Mac SMB.
Conversely, can the path for images be pointed to a network share on a NAS?
Thanks for any help you can provide!

**Comment by magdesign** [comment]
Here a tutorial on how to make a samba share: https://vimeo.com/227134211
You can mount your external NAS for example in /media/nas
(ask google on how to mount a NAS within debian jessie, there are many tutorials).
Then you have to change the path in the script under /var/www/sync/xsessionslideshow
from: /media/internal/images/* to the location where you mounted your NAS.
Next time you play the slideshow, it should play from your NAS.
