### ISSUE TITLE
create fake keyboard

### ISSUE THREAD

**Issue by pietrondo** [magdesign/PocketVJ-CP-v3#3]
It is not clear how to create the fake keyboard...

in the link http://www.fsays.eu/Blogging/Blog/Details/23
I see some code but.. how to compile it?
it is "c"?

thx

**Comment by magdesign** [comment]
Hi
Just read the blog post: http://www.fsays.eu/Blogging/Blog/Details/23 and do every step as described. Nothing to compile, just writing scripts.

**Comment by pietrondo** [comment]
but fsaysuinput is not:
`// open a device file descriptor
fd = open("/dev/uinput", O_WRONLY | O_NONBLOCK | O_CREAT);
// specify with keys are allowed
for (i=0; i < 255; i++)
{
ioctl(fd, UI_SET_KEYBIT, i);
}
memset(&uidev, 0, sizeof(uidev));
// fill the device descriptors
snprintf(uidev.name, UINPUT_MAX_NAME_SIZE, "uinput-fsays");
uidev.id.bustype = BUS_USB;
uidev.id.vendor = 0x1;
uidev.id.product = 0x1;
uidev.id.version = 2;
write(fd, &uidev, sizeof(uidev));
// create the device
ioctl(fd, UI_DEV_CREATE);`
?

**Comment by pietrondo** [comment]
ok from http://www.fsays.eu/Blogging/Blog/Details/27 i have downloaded a zip with the file to put in /opt/ chmod +x them... but nothing.

**Comment by magdesign** [comment]
all you have to do is to copy fsayskeyboard and fsayuinput to /opt.

**Comment by pietrondo** [comment]
ok and do I need to create
'/etc/init.d/fsaysuidev'?

**Comment by magdesign** [comment]
yap.

crate a file with the name: fsayauidev
content of the file you find on http://www.fsays.eu/Blogging/Blog/Details/23 in the second code window.

**Comment by pietrondo** [comment]
ok! I have created... but nothing..
I have tried to run the  scripts in sync directory (for examples mapper2e) this is my output:

![selezione_295](https://cloud.githubusercontent.com/assets/6080662/15802578/d8446014-2ab6-11e6-8154-0413cab77eda.png) 

Nothing.. the screen doesn't change (I have also tried with pi user).

thx for the help

**Comment by magdesign** [comment]
ok. Dont know whats wrong on your side.
Here you can download the files: 
http://pocketvj.com/downloads/fsaysuinput
http://pocketvj.com/downloads/fsayskeyboard
Then try it directly from the control panel.

**Comment by pietrondo** [comment]
ok thx

Pietro Capriata

http://www.pietrocapriata.me

CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

**Comment by pietrondo** [comment]
nothing.. same errors (doesn't work).

I have modified the /home/pi/openFrameworks/addons/ofxPiMapper/src/Application/ProjectionMappingState.cpp but nothing.

Any new ideas?

**Comment by magdesign** [comment]
is this still an issue or could you fix?

**Comment by pietrondo** [comment]
sorry.. I re do it. and same problem.

**Comment by pietrondo** [comment]
ok. i have tried without pocketvj.
works only "enter" key and the arrows keys

**Comment by pietrondo** [comment]
SOLVED! I change locales under raspi-config in        │    [*] en_GB.UTF-8 UTF-8                                                                                                                                                                                      
and now works!

**Comment by magdesign** [comment]
Great!
