### ISSUE TITLE
autostart not working

### ISSUE THREAD

**Issue by mandelbrotmedia** [magdesign/PocketVJ-CP-v3#31]
Hi,

today i updated to 1.14c and now the autostart feature doesn't work.
I activated "videoplayer master" in the autostart section but after a reboot there is only a black screen.
After i click on "play master loop" the video starts without any problem.

**Comment by magdesign** [comment]
After updating, go to the Display settings and click "Reset Default" and reboot.
Now it should work, if not, stop all tasks and make the update again.

Wait until the update is really finished, then "Reset Default" again and reboot. 
Report back, thanks.

**Comment by mandelbrotmedia** [comment]
Thx for your advice. But it didnt work.
I figured out that this behaviour only appears with one specific file.
Maybe there went something wrong with adobe media encoder.
I try to convert it with mpeg streamclip and report back asap

**Comment by magdesign** [comment]
It might also be only the naming of the file.. no ä ö ü è é etc. and no empty spaces.

**Comment by mandelbrotmedia** [comment]
It seeams pocketvj doesnt like files from adobe media encoder anymore. I always did it that way before and had no problems.
But with mpeg streamclip it works without any problems.
Thx for your help
