### ISSUE TITLE
force composite

### ISSUE THREAD

**Issue by meatballyoga** [magdesign/PocketVJ-CP-v3#32]
hi there,

is there a way to foce composite out with the raspberry pi 3 Pvj?

thanks

**Comment by magdesign** [comment]
PocketVJ 3.x  does not officially support composite out.
But you can manually edit /etc/boot.conf to make it working.

Comment out the hdmi lines and add the sdtv_mode lines: 

#hdmi_force_hotplug=1
#hdmi_drive=2
sdtv_mode=2
sdtv_aspect=1

Report back your working solution.
