### ISSUE TITLE
Videoplayer stops without reason

### ISSUE THREAD

**Issue by mandelbrotmedia** [magdesign/PocketVJ-CP-v3#34]
Hi,

I have 3 RPIs runing in master-slave seeamless sync mode. After a few hours (10 or more) one of the players (not always the same RPI) stops playing the video. It is fully working (interface, testscreen ... is all working).
If i hit play again it starts playing video again.
Are there any log-files for the omxplayer where i could find a reason?

**Comment by magdesign** [comment]
Is maybe your router resetting the connections? or do you still have some tasks in the scheduler?
Are your movies shorter than 30 seconds?

You can find log files in /var/log/

**Comment by mandelbrotmedia** [comment]
I have no router in my setup. Only a switch. And i dont have any tasks in the sheduler.
The movies are about 17min. long.

I couldnt find any helpfull log there. Is there a specific omxplayer log anywhere?

**Comment by magdesign** [comment]
Weird, this should not happen.

I just figured out that you have to send the -g flag with omxplayer to generate a log file.
For doing this, please edit the startmaster and startslave scripts in /var/www/sync/ and add the -g flag:

#start master
/usr/bin/omxplayer-sync -mug -o hdmi /media/internal/video/* > /dev/null 2>&1 & echo $! &

#start video as slave
/usr/bin/omxplayer-sync -lug -o hdmi /media/internal/video/* > /dev/null 2>&1 & echo $! &

The log file will be  in /usr/bin/omxplayer.log

**Comment by magdesign** [comment]
I just made an update to CP 1.14d and packed in the newest omxplayer build.

Please install the update and then go to Control Panel and hit Update Firmware.
I hope this will fix the problem.

**Comment by magdesign** [comment]
any news on this, did the omxplayer update help?

**Comment by mandelbrotmedia** [comment]
The RPIs are now productive. I solved it with a little programmable timeswitch which cuts the power every night.
I try to build the same setup again with the new update on the weekend and give you back some feedback:-)

**Comment by mandelbrotmedia** [comment]
I now updated to 1.14d and added the -g parameter. Now the players stop every hour. And there are no logs (omxplayer.log)
I tried to add sudo and sudo -u pi in front of the command but with no result.
How can i enable the logs?

**Comment by magdesign** [comment]
Damn it.
Somehow the omxplayer.log file gets written to to the directory from where you start omxplayer and you have to start it manually from command line. Sorry, I did not realize that, its a bit bad documented.
Use the commands given on post number 4 and start all the players via ssh thru the command line.

Meanwhile I will build a setup here and test this behavior, hope to figure out a solution.
If the newer omxplayer is not stable, I will revert to the old one or compile the newest by myself.

**Comment by magdesign** [comment]
Just for debugging purpose:
To make sure its nothing on the network side:
- If you directly connect the master with the slave via RJ45, does it run longer than 1 hour or is it the same behavior ?
- Do all PocketVJ have their own IP adress ?
- Do you use copied sd cards, self build ones or  original PocketVjs from the store?

I do have 2 PocketVJs running in sync over a router with the new Omxplayer for 3 hours now.... they are still in sync.

**Comment by magdesign** [comment]
I tested now the same setup for over 36hours and they are all still in sync.
I guess you have a network setup issue....

**Comment by mandelbrotmedia** [comment]
Hi,

now i have some logs when the player stopped working.
But i cant find any hint except this:

`03:04:07 T:1401466981 WARNING: Unhandled dbus message, member: NameAcquired interface: org.freedesktop.DBus type: 4 path: /org/freedesktop/DBus`

Could this be the reason for stopping?
(i also change the switch but with the same result)

**Comment by magdesign** [comment]
As i see in my docs, you bought one SD card and then I guess you made copys out of it.
I am pretty sure you messed something with the IP addresses and thats way it is crashing.

**Comment by magdesign** [comment]
Could you fix this by editing your network configuration?
