### ISSUE TITLE
wired connection with rj 45

### ISSUE THREAD

**Issue by pramodmadhav** [magdesign/PocketVJ-CP-v3#37]
I have purchased SD card with Pockectvj Software.
I was able to connect and see control panel and play some videos with WIFI connection. But I am not able to see the control panel with wired connection (RJ45). The IP address is  given by you with the SD card.
What could be the reason for this.

**Comment by magdesign** [comment]
How are you connectiong with RJ45,
direct connection to your computer or with a router between?
If you direct connect with your computer, you must give your system a fixed IP in the range of 192.168.2.*** 
If you have a router, it must be set to 192.168.2.1

**Comment by pramodmadhav** [comment]
I have tried that already which is written in your manual.
I have given my system fix IP address as 192.168.2.111.
Still it is not showing control panel on my laptop.
am I missing some thing?

**Comment by magdesign** [comment]
Connect via Wifi and go to ControlPanel AUX, click show RJ45 Ip, what is the output?

**Comment by pramodmadhav** [comment]
RJ 45 IP shows 192.168.2.101

**Comment by magdesign** [comment]
ok. this is good.
If you can not direct connect with computer with static IP address to 192.168.2.101 you must use
a router between both devices.

**Comment by pramodmadhav** [comment]
Is it designed like that or is there any problem with my system?
Because while using WIFI there is no router in between. 
And finally I want to use it in a closed privet network. So if required I may use Switch . Why router?
If it is must I have no problem using a router.
Thanks

**Comment by pramodmadhav** [comment]
OK I am able to see the synchronized test files.
I would like to have a control as follows
--.> power up both master and slave at the same time 
--> send command on network to start the master player and -->slaves will sync with the master

**Comment by magdesign** [comment]
So you figured out the direct connection with RJ45?
What was the problem?

About the Tcp commands, read manual on page 36.

**Comment by pramodmadhav** [comment]
Well I did not figured out the problem. I still can not see the control panel through RS45 cable.
What I did was I configured the master and slave through WIFI, then connected the the RJ 45 cables through network switch  and played the video through master using wifi connection.
I have seen those(page 36) command
My problem is I want to Power Up all the players at the same time.
Master will wait for the TCP command to start the video.
And all slaves will follow the master.
I do not want to use the control panel
How can I do it?

**Comment by magdesign** [comment]
I tried it with a macbook pro, RJ45direct connect to a PocketVJ.
In the Network settings in OSX: DHCP with manual Address: 192.168.2.200
Then open webbrowser and type RJ45 Ip of PocketVJ, e.g.: 192.168.2.101
The Controlpanel appears and is fully usable. 
So it must be something in your network configuration which is wrong. Try to disable internet and wifi and unplug all other devices to test it without any other thing which can cause failure.

About remote control without controlpanel:

In your case I would set the PocketVJ to autostart in scheduler mode, so they boot up and do nothing.
Then you can send via terminal from your computer (not the terminal from PocketVJ!):
`curl -s http://192.168.2.101/backend.php/?action=startslave`
`curl -s http://192.168.2.100/backend.php/?action=startmaster`

**Comment by pramodmadhav** [comment]
Ok Thanks for the replay.
I will recheck my network configuration and let you know.
About using without control panel:
I want to send command only to master.
In case you have two or more slaves I do not want to send command to all slaves, master should take care of that.
So when I send command to master, all players should start playing sync with each other . 
Is it possible?
One more question
If I configure pocketvj as master through control panel. does it remain master even for the next boot? or I have to do it again through control panel. If it is so what is the way out

**Comment by magdesign** [comment]
Yes it is possible, set the slaves to slave.
Autostart remains.
Please read the manual and try things out, you will figure things out pretty fast, its not that complicated.
