### ISSUE TITLE
Image Player and Mapper not working

### ISSUE THREAD

**Issue by Audiogeek1974** [magdesign/PocketVJ-CP-v3#39]
I have been working on building a Pocket VJ from scratch. I followed all of the instructions, but can't seem to get it to work. I see responses in the control panel and can play audio test tone and the test pattern. However, nothing plays when select "Play Master Loop".

When I click "Play Master Loop", the screen goes blank and there is a blinking underscore cursor at the top left of the screen. When I select "MAPPING Mode" then I see the number 3. Add Quad gives me a "q", Add Triangle does nothing, Add Gridwrap gives me a "g" but nothing else ever happens. Sometimes, if I click a button I will see a letter just repeat continuously across the top of the screen.

I read in another post about needing to start X, however I started with Raspbian Lite as the instructions indicated, which didn't install a graphical interface. I manually installed xserver-xorg but it still does not work. When I manually type in start x, I get this response:

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.26-v7+ armv7l Raspbian
Current Operating System: Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l
Kernel command line: bcm2708_fb.fbwidth=1680 bcm2708_fb.fbheight=1050 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=PARTUUID=059b6d0f-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
Build Date: 11 November 2016  11:59:59AM
xorg-server 2:1.18.4-2+rpi1 (https://www.debian.org/support)
Current version of pixman: 0.33.3
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/pi/.local/share/xorg/Xorg.0.log", Time: Sat Dec 23 21:43:50 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/home/pi/.local/share/xorg/Xorg.0.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error
Couldn't get a file descriptor referring to the console

Any help would be greatly appreciated.

**Comment by magdesign** [comment]
Are you able to start a video from commandline?
e.g.:` /usr/bin/omxplayer-sync -mu -o hdmi /media/internal/video/*`

Did you install openframeworks in:` /home/pi/openframeworks/` ?

Did you check user rights for the scripts in` /var/www/sync`?
You can try putting putting the CP update in /internal and then in ControlPanel click: `UPDATE Everything`
This should install the videoplayer, scripts, and fix user rights.

About the image player: https://github.com/magdesign/PocketVJ-CP-v3/issues/18

**Comment by Audiogeek1974** [comment]
I tried starting one of the videos that I pulled from the pimapper example project using:
omxplayer-sync -mv test.mov
(tried with the .mp4 files as well with same results)

and I get this error:
WARNING: dbus connection could not be established
org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.omxplayer was not provided by any .service files
WARNING: omxplayer did not start. Try to test with `omxplayer -s OPTIONS`

If I try to launch it with the file from the turningmachine install instructions using:
omxplayer-sync -mv synctest.mp4

And it plays just fine.

I do have openframeworks in /home/pi/openFrameworks/ directory.

All of the scripts in /var/www/sync have:
-rwxr-xr-x

I tried downloading and applying the update file. The same results mentioned above still happen. Even tried reinstalling the dbus per turningmachine instructions.

Now, also for some reason the Apache2 Debian Default page is showing up instead of CP when I access through a browser. I checked the /etc/lighttpd/lighttpd.conf file and it still has "/var/www/" as the document root.

Thanks,
Jason

**Comment by magdesign** [comment]
try it with reinstalling python-dbus

**Comment by Audiogeek1974** [comment]
I made some progress, but am now stuck again. I couldn't even get ofxPiMapper to compile and run by itself. I started with a new SD card and fresh install on everything. After working through some kinks with ofxPiMapper, I was finally able to get it to compile/run the example. After that, I finished the rest of the required items for PocketVJ. I was able to launch the control panel just fine and start videos and image player. Still could not get the mapper to work. I downloaded latest master .zip file and did "update everything" then after that "update mapper". After that, the mapper would launch with 1 frame running a slideshow of images, but I couldn't get it to go into any set up modes.

I read on another issue where it was recommended to "factory reset" and then "update mapper". I tried this, and now I can't get to the control panel anymore. I go to the IP address and just see the Apache2 default page. Manually typed <ip address>/index.html and still only get the Apache2 default page. I went into /var/www and cat index.html and made sure it is the correct CP file. How do I get the CP back?
Thanks!

**Comment by Audiogeek1974** [comment]
I tried edge instead of chrome and it worked on edge. Tried from safari as well on my ipad and it worked. Then went back to chrome and it was working correctly. I have no idea what happened.

**Comment by magdesign** [comment]
So this issue can be closed?

**Comment by Audiogeek1974** [comment]
Apologies for the delay. Yes. You can close it now.
