### ISSUE TITLE
sync in mapping mode

### ISSUE THREAD

**Issue by mandelbrotmedia** [magdesign/PocketVJ-CP-v3#4]
Is it possible to use the sync function while in mapping mode? I want to use 3 raspis synced in mapping mode.

**Comment by magdesign** [comment]
Currently its not possible to use the sync function in mapping mode.
We are working on it and hope to bring out a solution soon.

Until then you can use the Syphon function to use the PocketVJ as a wireless display, render out the mapped video part from your mapping software and play it with the regular sync function. 
https://vimeo.com/192291861

**Comment by magdesign** [comment]
https://github.com/jvcleave/ofxOMXPlayer/issues/96

**Comment by mandelbrotmedia** [comment]
Thanks for the syphon hint!
But iam not able to get a syphon stream into the pi.
iam working with resolume. the syphon client on my macbook showed me the right output.
but the pi stays black.
i tried direct RJ45 wireing and i tried a router with DHCP enabled.

do you have a solution?

**Comment by mandelbrotmedia** [comment]
and yes, the syphon server was up before the pi booted

**Comment by magdesign** [comment]
Just to make sure:

- Your computer is only connected to one network
-  Tcpsyphon server is installed
- Route Resolume Output to Tcpsyphon server
- Be in the same network as the PocketVJ is (Router must be 192.168.2.1), maybe first try it when connected to vj100 Wifi.
- Connections can sometimes take a while, if not, just manual restart "TCPSyphon Start" in CP.

https://vimeo.com/192291861

**Comment by magdesign** [comment]
It is possible to sync mapping with the PocketVJ Exhibition:
https://www.pocketvj.com/pocketvj-exhibition

also softedge and fullscreen.
