### ISSUE TITLE
Play_06 Once button not working

### ISSUE THREAD

**Issue by Audiogeek1974** [magdesign/PocketVJ-CP-v3#40]
The code for this button appears to be missing from backend.php

if ($_GET['action'] == 'startmasteronce05') {
	exec("sudo /var/www/sync/startmasterone05");
	$outputtext = "start video 05 once";
}
if ($_GET['action'] == 'startmasteronce07') {
	exec("sudo /var/www/sync/startmasterone07");
	$outputtext = "start video 07 once";
}

**Comment by magdesign** [comment]
Thanks.
Fixed and updated missing code in backend.php
