### ISSUE TITLE
How to make the PVJ securely accessible over the internet?

### ISSUE THREAD

**Issue by UnlimitedVideoStaging** [magdesign/PocketVJ-CP-v3#41]
We'd like to be able to use the pocketvj to feed a screen at an event and administer it from the office. In our testing, we gave it an internet connection with a static ip and portforwarded to the pi, allowing us control, however it needs to be password protected. I've tried implementing apache2's htaccess, however I have not been able to make it work. All the pieces seem to be in place, but it never asks for the password. Any thoughts on using .htaccess with the pocketvj, or maybe another method that would work?

Thank you

**Comment by magdesign** [comment]
If you want to password protect with .htaccess you would have to put all files from /var/www/ into a subfolder /var/www/subfolder/ then you can pw protect this. I realized that too late and did not change it too keep downwards compatibility. You would then have to update all paths in backend.php

**Comment by magdesign** [comment]
Could you solve this?

**Comment by UnlimitedVideoStaging** [comment]
I was unable to get it working using apache2, but the lighttpd.conf file just needs a section to be uncommented and you get password protection.

**Comment by magdesign** [comment]
Could you tell the community what you modified in lighttpd.conf ?!

**Comment by magdesign** [comment]
see here:
https://www.cyberciti.biz/tips/lighttpd-setup-a-password-protected-directory-directories.html
