### ISSUE TITLE
The internal Time goes wrong

### ISSUE THREAD

**Issue by Mingual123** [magdesign/PocketVJ-CP-v3#42]
To programm a scedule I need to have the right internal time. How can set it?

**Comment by magdesign** [comment]
As a customer of an SD card only, you provide your own RPi as well as your own RTC.

**Comment by Mingual123** [comment]
So I changed the time successfully !  What it RTC?

**Comment by magdesign** [comment]
https://github.com/magdesign/PocketVJ-CP-v3/issues/25
