### ISSUE TITLE
Clear Hidden Files does not delete the hidden Files

### ISSUE THREAD

**Issue by Mingual123** [magdesign/PocketVJ-CP-v3#43]
I tried all possibilities to delete the hidden Files whoch are made when using USB Sticks with Mac. Neither the function " Clear Hidden Files" nor deleting manually worked.
For that reason the playfunction "Play 01 Loop etc doenst work.

**Comment by magdesign** [comment]
I just updated CP to version 2.3.3a to execute the clean command also on usb sticks.
https://github.com/magdesign/PocketVJ-CP-v3/blob/master/RELEASE_NOTES.md
