### ISSUE TITLE
Play Loop Control seems to work only with internal Movies

### ISSUE THREAD

**Issue by Mingual123** [magdesign/PocketVJ-CP-v3#44]
I have several videos on a USB-Stick (NTFS). The MASTER PLAY USB works fine. But When I want to loop Video 03 from USB than the screen is black. It seems as if I can only Loop all Videos from USB not particular one!?!
Thanks for your help
Thomas

**Comment by magdesign** [comment]
For the moment, Play_0x Loop is only coded for videos stored on internal storage.
If you want to change them to usb, you would have to change  all `startmaser0x `scripts in` /var/www/sync/`
for example for `Startmaster01`: 

`/usr/bin/omxplayer-sync -mu -o hdmi /media/internal/video/01* > /dev/null 2>&1 & echo $! &`

change the path to:
`/usr/bin/omxplayer-sync -mu -o hdmi /media/usb/01* > /dev/null 2>&1 & echo $! &`

If you do so, please contribute the files, so I can implement the function in the next CP update.

**Comment by Mingual123** [comment]
How can I change it? Where should I navigate to? within the terminal? Thanks a lot! I have only very basic knowledge in Raspberry so I will learn. 
Thomas

**Comment by magdesign** [comment]
With CP 2.3.4 there are two scripts to load video 01_* and 02_* from usb:
/var/www/sync/startmasterusb01
/var/www/sync/startmasterusb02
