### ISSUE TITLE
Scheduler/Timer: how can I program autostart from USB or Internal?

### ISSUE THREAD

**Issue by Mingual123** [magdesign/PocketVJ-CP-v3#45]
I have a exibition for about 30 days. For every Day I need to loop one particular video. Every Days the video changes. The internal Memory is too low to save all videos. I need to load them from USB and Internal. But the Code uses only "autostart Master" . How can I decide to switch between Internal and USB? Thanks
Thomas

**Comment by magdesign** [comment]
You can autostart videos from usb in Scheduler with following command:

/var/www/sync/startmasterusb
