### ISSUE TITLE
I need slow Crossfades between Slideshow 4K Photographs 

### ISSUE THREAD

**Issue by Mingual123** [magdesign/PocketVJ-CP-v3#46]
I have 1440 Photographs which should morph slowly from one to the next. The idea is to programm very long slideshow (within one year or even two years)
I want to let decay a wax figure whithin one ore two years. and I dont want to see the hard cuts between the photographs. For that reason I need a cross fade of maybe 20 Seconds.
When the power is set off the the progress of morphing should stay. If I switch on the Raspberry the progress should continue as a hidden process.
Thanks a lot!
Thomas

**Comment by magdesign** [comment]
Photographs should not exceed 1920x1080 pixel.
Then load them to the` /internal/images/` folder.
Startup Mapper and use the slideshow source.
To change the slideshow transition time, edit:
`/home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/magslideshow_settings.xml`
under` Dissolve` there is a variable `Duration`, change it from` 3` to `20` to get 20 seconds of dissolve.
Make sure that` SlideDuration` is always set a higher value than the dissolve time.
