### ISSUE TITLE
When videos are more than 12 on internal storage than the Schedule Function doesnt work

### ISSUE THREAD

**Issue by Mingual123** [magdesign/PocketVJ-CP-v3#47]
The Schedule works fine when you use only 12 Videos. When you have more than 12 Videos than the Schedule doesnt support that. That`s pitty. 
I have 30 Videos to show. 
Any help?

**Comment by magdesign** [comment]
For the moment there are only 12 pre defined Play_0x loops.
More predefined buttons may come in future if needed by a certain amount of users.

You can simply copy this scrip: `https://github.com/magdesign/PocketVJ-CP-v3/blob/master/sync/startmaster01` and save it for example as `startmaster13 `and edit the content to `/usr/bin/omxplayer-sync -mu -o hdmi /media/internal/video/13* > /dev/null 2>&1 & echo $! &`

If done so, all users are happy if you contribute the scripts.

**Comment by magdesign** [comment]
With update 2.3.4
you have scripts up to 16_*
