### ISSUE TITLE
When Schedule is programmed to play File 5_ it won`t be looped

### ISSUE THREAD

**Issue by Mingual123** [magdesign/PocketVJ-CP-v3#48]
I want to let loop a particular Video via Schedule. It doesnt seem to work with that command:

0 6 6 2 4 /var/www/sync/startmasterone05
It just plays it once. I need an seamless loop!!!!

Is there a command to do that?
Thanks for your help
Thomas

**Comment by magdesign** [comment]
`/var/www/sync/startmasterone05`
Is the command to play the video only once, thats what the `one` in the command stands for.

If you want to loop video 05 you need following command:

`/var/www/sync/startmaster05`

Please do not spam this forum with inappropriate error reports which do not exist.
As we talked on the phone, customers who only buy the image on SD card do not get premium support. Support includes implementing new features in a short term, as well as responses via email and phone.
