### ISSUE TITLE
Schedule doesn`t work when time was set in the past

### ISSUE THREAD

**Issue by Mingual123** [magdesign/PocketVJ-CP-v3#49]
I programmed the schedule to start a video at six o clock, as a loop for 12 houres
﻿0 6 6 2 2 /var/www/sync/startmasterone01

When the guy of the gallery switches on the raspberry at 8 o clock, than the PVJ doesnt look at the timeschedule which video is supposed to be played. It stays black! It should look in the schedule and play that particular video which must be played during that 12 houres period.
Any ideas?
Thomas

**Comment by magdesign** [comment]
As already mentioned here: https://github.com/magdesign/PocketVJ-CP-v3/issues/42
You have missing hardware which is not a fault of the PocketVJ software.
