### ISSUE TITLE
Wishlist for future versions

### ISSUE THREAD

**Issue by brendanbercik** [magdesign/PocketVJ-CP-v3#5]
PocketVJ looks like a stellar product & piece of software! Here are 2 features I would love to have with PocketVJ (that I can come up with off the top of my head):

**1.) Masking:** beyond just warping/mapping, it would be great to create black masks that occlude certain regions of the video.

**2.) Bezier curve/circular/spherical mapping:** this may be complicated to implement, but Paul Bourke's meshwarpserver may be able to guide you in the right direction (or perhaps even provide the code you need).

Feel free to respond with the features you wish to see implemented into PocketVJ!

**Comment by mandelbrotmedia** [comment]
It would be nice to hava sync-function in seamless-loop-mode

**Comment by magdesign** [comment]
- The seamless loop sync function would be pretty easy to make, the regular sync function has a little delay caused by passing the playlist. I just put It on the roadmap.
- For masking in mapping mode: So far as workaround you can use a black image as input and layer it on top.
-  Bezier curve/circular/spherical mapping would be great, I know, dreaming of it too. Maybe I will really contact Paul...

**Comment by magdesign** [comment]
Working on an import script to import .svg files done in other mapping software to run on PocketVJ.
Need some help in the coding..check it out here: https://github.com/magdesign/mapping-converter

**Comment by brendanbercik** [comment]
Very impressive!

Is the idea here to simplify the mapping process, so that users don't need to use Syphon Recorder to re-record their compositions when using third-party mapping software?

Instead the user could just export .SVG from their mapping software and upload it to the PocketVJ mapper as a polygon layer?

**Comment by magdesign** [comment]
Exactly.

**Comment by magdesign** [comment]
@mandelbrotmedia :
Sync in seamless mode should work now!
Update to the newest CP version 1.13a, hit "factory preset", put only one video into the video folder, click "master loop" and it should seamless loop and sync.
Please test report back!
I will remove the seamless button in the next number release.

**Comment by Prepete** [comment]
What about an option to "clean" autostart script?

**Comment by magdesign** [comment]
what do you mean with clean? 

You can autostart into "scheduler mode" if there nothing should autostart.

**Comment by Prepete** [comment]
What about implementing an Artnet-/DMX-trigger for sync player or mapping mode? 

I also think it would be wonderful to get transitions between triggered videos.

**Comment by magdesign** [comment]
DMX is integrated with OLA. I do not not have a DMX to USB input by hand, also have no hardware to send DMX signals,  but its quite easy to write a script which triggers your desired function over OLA: https://opendmx.net/index.php/OLA_DMX_Trigger
For the execute commands just use the commands from the scheduler.
Please contribute.

**Comment by xniala** [comment]
It would be great to trigger mapping tools with OSC.
For instance having the ability to display a video file remotely choosen in a mapped surface.

**Comment by xniala** [comment]
Another idea : having the ability to choose Syphon (or Spout) server, with a drop menu for instance, when several TCPSyphon Server (or Spout) are running.
Regards

**Comment by sanddk** [comment]
Is there a possibility to use a dynamic website as the input for a mapping surface?

**Comment by magdesign** [comment]
Not yet (with ofxPiMapper).
But we are currently coding a new mapper which will have this feature and many other inputs.
If you cant wait I could deliver a pre alpha version in PVJ 3.6 release.
https://mapper.jku.one/

**Comment by sanddk** [comment]
That would be great!

**Comment by sanddk** [comment]
Hi magdesign, I would be happy to try out your pre alpha version to test the use of a website for input.

**Comment by magdesign** [comment]
can you please contact my via email.

**Comment by magdesign** [comment]
just released image 3.6
see release notes.
remember that pre-alpha is a very early state in developing.

**Comment by Prepete** [comment]
Maybe you could implement piFM?
This is a project to turn a pi into an ukw transmitter...
http://www.icrobotics.co.uk/wiki/index.php/Turning_the_Raspberry_Pi_Into_an_FM_Transmitter

**Comment by Prepete** [comment]
integrate cec-utils to control TV trough HDMI cable.
https://packages.debian.org/de/jessie/cec-utils

**Comment by frankbash** [comment]
USB Support for Midi 
So when you hook up a usb midi device you can start the /startmaster01 and so on,
Maybe usb hid for a standard numbers pad could start this too, this will be great for exhibition or GPIO can do this

**Comment by frankbash** [comment]
> Another idea : having the ability to choose Syphon (or Spout) server, with a drop menu for instance, when several TCPSyphon Server (or Spout) are running.
> Regards
hey you can use 1 tcp syphon stream to maybe 4 pocket vis with running tcp syphon client on each and do some kind of pixel mapping (like on led walls)

ex.: send a 1920 x 1080 stream via syphon to the pocketvjs with a test picture 

all got the same pic

now you can ssh to pocketvj number 1 and enter this command : 

sudo /usr/bin/TCPSClient.bin -s 0,0,0.5,1
pocketvj 1 show now only the left half of you stream

go back to fullscreen:

sudo /usr/bin/TCPSClient.bin -s 0,0,1,1

here more commands to test:

right half= 					sudo /usr/bin/TCPSClient.bin -s 0.5,0,1,1

upper half	 						sudo /usr/bin/TCPSClient.bin -s 0,0,1,0.5 

lower half						sudo /usr/bin/TCPSClient.bin -s 0,0.5,1,1

2x2 mean 4 pocketvjs 2 wide and 2 high (test it with some monitors)

2x2 top left  						sudo /usr/bin/TCPSClient.bin -s 0,0,0.5,0.5 

2x2 top right 						sudo /usr/bin/TCPSClient.bin -s 0.5,0,1,0.5

2x2 down right						sudo /usr/bin/TCPSClient.bin -s 0.5,0.5,1,1 

2x2 down left						sudo /usr/bin/TCPSClient.bin -s 0,0.5,0.5,1

i hope magdesign add this commands to the cp 

have fun

**Comment by magdesign** [comment]
Just diving into the midi stuff.
Installed puredata, I think with this it should be possible to map midi commands to the CP.
The Syphon thing looks interesting too, but what for would one need this?

**Comment by frankbash** [comment]
the syphon is for live video walls here some tests:

part 1 https://youtu.be/PLybGP_hcxY
part 2 https://youtu.be/pwtgXBvq0GM

even vlc player (the syphon version) works and all via network

**Comment by frankbash** [comment]
and midi would be great, for all which need a work around try https://osculator.net you can translate from midi to osc commands

**Comment by magdesign** [comment]
@Prepete : sudo apt-get install cec-utils
installed since PVJ3.75, what would you want to do with cec-utils?

btw:
piFM will not be added, there is no use case...

**Comment by magdesign** [comment]
with amidi -l you can list your connected midi devices.
I am not quite sure yet how to map a certain midi in command to a terminal command..... maybe someone can help...

**Comment by frankbash** [comment]
Hey i find this about Midi and a pi 
https://www.instructables.com/id/PiMiDi-A-Raspberry-Pi-Midi-Box-or-How-I-Learned-to/

**Comment by magdesign** [comment]
We do not want to build a midi interface nor playing synthesizers, PVJ already supports plug'n'play usb midi devices. If we integrate midi support, it should be used for triggering a video with a note on/off command.

**Comment by frankbash** [comment]
And maybe this will help too
https://www.raspberrypi.org/forums/viewtopic.php?t=205773

**Comment by frankbash** [comment]
That’s exactly what I mean, trigger only video, in the tutorials is only the software interesting

**Comment by frankbash** [comment]
hey everybody, midi 2 terminal or command is solved!!!!!!
so everyone can hook up a midi controller or keyboard to the pi and start video loops( or all what's in the backend.php) install https://github.com/SpotlightKid/python-rtmidi by Chris Arendt and use the
https://github.com/SpotlightKid/python-rtmidi/tree/master/examples/midi2command
so when you press a note on the controller rtmidi translate and send it,
you can config the example.cfg start the midi2command python script and go wild
![img_0676](https://user-images.githubusercontent.com/6725467/50984525-72b39380-1502-11e9-8b31-a542f561a493.jpg)
<img width="807" alt="bildschirmfoto 2019-01-10 um 17 15 36" src="https://user-images.githubusercontent.com/6725467/50984526-72b39380-1502-11e9-8717-86f15e017890.png">
<img width="882" alt="bildschirmfoto 2019-01-10 um 17 15 49" src="https://user-images.githubusercontent.com/6725467/50984527-734c2a00-1502-11e9-973f-3debf3eab647.png">
<img width="977" alt="bildschirmfoto 2019-01-10 um 17 32 55" src="https://user-images.githubusercontent.com/6725467/50984528-734c2a00-1502-11e9-99ea-0050154370ac.png">
<img width="877" alt="bildschirmfoto 2019-01-10 um 17 48 50" src="https://user-images.githubusercontent.com/6725467/50984530-734c2a00-1502-11e9-9c18-01822ce08019.png">
<img width="865" alt="bildschirmfoto 2019-01-10 um 17 49 26" src="https://user-images.githubusercontent.com/6725467/50984532-73e4c080-1502-11e9-8143-fbdba5eaeb85.png">
<img width="599" alt="bildschirmfoto midi-probe" src="https://user-images.githubusercontent.com/6725467/50984534-73e4c080-1502-11e9-9fd4-06814f640308.png">

**Comment by magdesign** [comment]
Great work! 
Thanks a lot, thats why we all love opensource :-)
Will add this to the next CP release.

**Comment by frankbash** [comment]
and the big thing is that rtmidi support osc too ( but i fuck it up :( during installation  ) so you could send from midi input on pocket vj 1 to all others via osc commands

thanks to all and special to https://github.com/SpotlightKid

**Comment by frankbash** [comment]
Hey its me again!!! My wish for future versions is: a Master Fader, so i can blend the output or fade to black via orc or midi???

**Comment by magdesign** [comment]
I will think about this, could be solved with overlaying a .png file and chancing the alpha... not quite sure yet... ;-)

**Comment by GabrioGi** [comment]
For future release i would like to propose a better gridwarp solution, with a high definined mesh and with a fix on the "add row" or "add column" that now resets all the warp.

**Comment by GabrioGi** [comment]
Another issue that I think could help for city installation, is the possibility to switch from wifi AP to wifi Client and have the possibility to add SSID and Pas-Key from the browser.

**Comment by magdesign** [comment]
@GabrioGi: Connect to Wifi is available on [PocketVJ Exhibition](https://www.pocketvj.com/pocketvj-exhibition)
@ frankbash: fading to black is now possible
@Prepete: Artnet-/DMX-trigger is available on [PocketVJ Exhibition](https://www.pocketvj.com/pocketvj-exhibition)
