### ISSUE TITLE
When working with Time Schedule and VideoPlayer- Videos seem not to be looped seamless

### ISSUE THREAD

**Issue by Mingual123** [magdesign/PocketVJ-CP-v3#51]
When working with Time Schedule I can choose wich video is being played (in loop)
But when checking this function, the videos are not looped seamless. Some of my videos work only when they are seamless so is there a solution?

**Comment by magdesign** [comment]
Stop all tasks.
Go to the Video Control section in CP and hit: Seamless
Now all videos will be looped seamless.
