### ISSUE TITLE
installing qlcplus to use with CP

### ISSUE THREAD

**Issue by Prepete** [magdesign/PocketVJ-CP-v3#52]
Hi there,
I run in problems installing qlcplus. Although everything is compiled and installed on my pi I'm unable to start it from CP. When I start an X-session I can start qlc and use it.

**Comment by magdesign** [comment]
can you start qlcplus from commandline under x with:
qlcplus -f

**Comment by Prepete** [comment]
Yes,
I only can start it when I'm in "desktop" mode. (ESC, sudo startx, from menu "run", "qlcplus -f")

**Comment by magdesign** [comment]
Are you using a PocketVJ built from scratch or which build number are you using (eg.: 3.3) ?
Are the other x related functions like Slideshow or VNC Screensharing working ?

**Comment by Prepete** [comment]
I bought an preconfigured SD card from you and tried to update it to the current version. How can I check the build number?
X related functions don't work.

**Comment by magdesign** [comment]
When PocketVJ is booting up, you will see logo and build number.
It looks like you messed something with X window system. 
Can you describe what all you did on the OS?

**Comment by Prepete** [comment]
I updated everything through aptitude, installed all necessary packages and followed your instruction from the README.md

The build is 3.1

**Comment by magdesign** [comment]
**never ever make a sudo apt-get upgrade !**
There is nowhere in the update instructions written you should do that!
If you do it will mess up some important things on the system. For example the whole X window system settings. For updating always use the update link from www.pocketvj.com and using the CP update function.
Is there any chance to revert what you did ?

**Comment by Prepete** [comment]
I can restore an image that I made before. How can I properly update my system to use QLC+, VNC, etc.?

**Comment by magdesign** [comment]
If you restore your backup image, VNC and all the stuff should work out of the box.
If you want to install QLC+ just install it with all dependencies written on their webpage, then it should also work out of the box. Remember not to make a sudo apt-get upgrade.

**Comment by magdesign** [comment]
Could you fix this issue?

**Comment by Prepete** [comment]
Everything is working fine now and I was able to restore pvj with my backup. Thank you for the support!
