### ISSUE TITLE
PocketVJ 3.x image does not boot on RPi 3 B+ (released on 14/03/2018)

### ISSUE THREAD

**Issue by magdesign** [magdesign/PocketVJ-CP-v3#53]
PocketVJ image will not boot on the newly released RPi 3 B+ (14/03/2018).

**Comment by magdesign** [comment]
Here is the solution:

- Insert card into RPi3
- sudo apt-get install rpi-update
- sudo rpi-update
- wget https://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/firmware-brcm80211_20161130-3+rpt3_all.deb
- sudo dpkg -i firmware-brcm80211_20161130-3+rpt3_all.deb
- reboot

Now it should also boot on RPi3 B+.

Note:
**Do not make** apt-get upgrade since this breaks some X window settings and image player will not work anymore!

**Comment by zimtzeke** [comment]
hi, for me this worked after some little changes:
	•	Insert card into RPi3
	•	sudo apt-get install rpi-update
	•	sudo rpi-update <— THIS DID NOT WORK (ca-error), SO I DID… (see next line)
	•	sudo CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt rpi-update
	•	wget https://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/firmware-brcm80211_20161130-3+rpt3_all.deb <— THIS DID NOT WORK, SO I DOWN-LOADED FILE on my remote computer AND UPLOADED IT WITH SMB TO /media/internal and executed it like this:
	•	cd /media/internal
	•	sudo dpkg -i firmware-brcm80211_20161130-3+rpt3_all.deb
	•	reboot

**Comment by Kolor3k** [comment]
1.Download:
https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-07-05/
https://github.com/raspberrypi/firmware
https://workupload.com/file/Mr6bBp2y
2.Flash rpi 2017-07-05-raspbian-jessie-lite.img
3.Delete all files located in Boot partition
4.Copy boot folder from firmware-master.zip
4.Replace Kernel .Files located in boot.zip
5.Boot rpi
6.sudo rpi-update
7.reboot
It worked for me
