### ISSUE TITLE
Projector not turning on according to timer settings

### ISSUE THREAD

**Issue by middletonarts** [magdesign/PocketVJ-CP-v3#54]
Although I've set up my schedule settings properly in the PocketVJ control panel, our projector still will not turn on and off according to the schedule we've set. What could be causing this?

**Comment by magdesign** [comment]
Can you manually turn it off with the "Projector Power Off" button in ControlPanel ?
If yes: can you manually turn it on ?
If yes: did you write the correct command in the scheduler =  "/var/www/sync/beameron"

If no: did you watch the tutorial on pocketvj.com, did you disable all security and power safe features?
