### ISSUE TITLE
How to loop video playlist from USB?

### ISSUE THREAD

**Issue by aaapoc** [magdesign/PocketVJ-CP-v3#57]
Hi,

Unless I'm missing something, I can't seem to loop a series of videos played from a mounted USB stick. When the last video finishes, I get a black screen. Ideally, it would be great if it would play the first video again and then the remaining playlist on  repeat. Is this possible?

**Comment by magdesign** [comment]
This works out of the box.
Make sure there are only your video files on the usb stick and nothing else.

**Comment by aaapoc** [comment]
Hi magdesign,

This doesn't appear to work still. This time, I'm just trying to loop one video played from the USB stick, but I get a black screen when it finishes. There are no other folders or files on the USB stick, just the movie file. The movie file plays correctly.

**Comment by magdesign** [comment]
I just checked this with a brand new USB stick, putting 2 videos on it.
It works with looping both videos endless.
I think you are using an Apple computer to put the files on the stick, if yes, you need to remove the hidden files OSX is writing to the drive, its something like __MACOSX.
Did you try to hit "Clean hidden Files" in the yellow section of the Controlpanel in PocketVJ?
Another solution would be using [this](http://szydlo.eu/2017/11/29/tool-for-removing-mac-dot-files-from-removable-media/) or [this](http://www.zeroonetwenty.com/blueharvest/).

You can also mount the USB stick on PocketVJ, then go to Filebrowser and check what files are on the stick, delete everything (folder, images, hidden files) except the videos.

**Comment by magdesign** [comment]
I fixed this with CP 2.4.4a
Whenever you hit `Play from USB`, PocketVJ will automatically remove the annoying OSX files.
Also updated the clean hidden files script with removing .Spotlight-V100 folder.
Please update.
