### ISSUE TITLE
converter folder user rights

### ISSUE THREAD

**Issue by frankbash** [magdesign/PocketVJ-CP-v3#58]
<img width="1401" alt="bildschirmfoto 2018-07-19 um 19 56 55" src="https://user-images.githubusercontent.com/6725467/42961187-5aad98a6-8b8e-11e8-8f51-c66b6bd0f41f.png">
is set to 755 where can i set it to 777???

**Comment by frankbash** [comment]
i fixed it myself by using:
to enter the terminal via web browser 
in chrome //"pocketvj ip":4200
the enter login and pass
after this enter this "sudo chmod 777 /root/internal/converter/ "
after browser refresh the folder got now the new user rights

**Comment by magdesign** [comment]
You can always click "Factory Reset".
This will fix all rights as well.
