### ISSUE TITLE
Problems with built-in wifi

### ISSUE THREAD

**Issue by mandelbrotmedia** [magdesign/PocketVJ-CP-v3#6]
I'm having problems with the built in wifi on a RPI 3.
the control panel takes about a minute to load completly.
is this normal?

**Comment by magdesign** [comment]
I fixed this issue yesterday.
Its not a wifi problem, its a line in the html code.
Please update to CP 1.05 and you will be fine.
You can update as described here: https://vimeo.com/187539934
(leave the last part, mapper and sync-script are already up to date)
