### ISSUE TITLE
PocketVJ on a PI ZERO or BeagleBone ?

### ISSUE THREAD

**Issue by earsneyes** [magdesign/PocketVJ-CP-v3#63]
Hi there,

is it possible to run on an PI ZERO WH (1 GHz, 512 MB RAM) or even on a BeagleBone Black/Green ?

I am asking because i want to pack it in a case as small as possible to pair it with a pocket Projector.

Thanks for your wonderfull work!
Cheers 
Linus

**Comment by magdesign** [comment]
It will not run on a BeagleBone since its a different hardware, with some changes on the image its possible to make it running on a RpiZero.

**Comment by earsneyes** [comment]
I abandoned this aproach.
