### ISSUE TITLE
help with customscript

### ISSUE THREAD

**Issue by Prepete** [magdesign/PocketVJ-CP-v3#65]
Hi there,
I need help executing my customized script. It's impossible to start an instance of OMXPlayer and synchronizing its current playback position to the internal time.
The video is 24h long and should be played on the requested, current time.

Here is my script:

#kill all running tasks
/var/www/sync/stopall &

#start omxplayer with current time
/usr/bin/omxplayer --loop --no-osd -o both /media/internal/video/01_st24.mov -l $(date +"%H:%M:%S") > /dev/null 2>&1 & echo $! &

Thanks for your support!

**Comment by magdesign** [comment]
Nice script :-)

Did you try to manually execute it in terminal without `> /dev/null 2>&1 & echo $! &` so you get a console output?

**Comment by Prepete** [comment]
everything works out fine when I trigger that script directly from the terminal. When put into an executable script nothing happens.

**Comment by magdesign** [comment]
did you make the script executable ?
sudo chmod +x /path/to/customscript

**Comment by ProjectileObjects** [comment]
Will it run if you comment out: `#/var/www/sync/stopall &`

**Comment by magdesign** [comment]
What I am wondering is how do you trigger the custom script, since there are only 2 buttons in CP for Autostart custom scripts, so you would have to reboot PVJ to get it triggered.

**Comment by Prepete** [comment]
For testing I‘ve modified the customscript trough a ssh session and I also triggered it through this session. On page „aux“ in cp you implemented a button for two custom function. So I wanted to combine both - autostart and for retriggering the button.
Later I’ll check the permission and try it by commenting out the „killall-function“.

**Comment by Prepete** [comment]
hi there,
everything is working out fine right now. I changed the permissions and deleted the "kill-process".
Trigger works fine on reboot and manually.
Thank you!

**Comment by magdesign** [comment]
I totally forgot about those buttons :-)
You should leave the stopall command, since this is essential to kill all running tasks.
Its quite sure that the problem was the permissions, so can we mark the issue as solved?

**Comment by Prepete** [comment]
yes, it's working now... I've put a delay of a few seconds between stopping all and playing back the 24h video... Thank you!
