### ISSUE TITLE
chmod +x startmaster09 ... 12

### ISSUE THREAD

**Issue by zimtzeke** [magdesign/PocketVJ-CP-v3#70]
dear marc-andre!

first of all - thanks for your work and the possibility to get the code from github!

i made a new build of pocketVJ according to your github readme 
everything is ok (despite osc as npm install osc-receiver does not work - found solution (see below)). 
ported it to Rpi-3b+ and works too. 

i encountered one bug in my installation (with v2.4.0e)

**BUG** does not play when sending tcp-command for startmaster09 ... startmaster12
e.g. GET http://192.168.105.34/backend.php/?action=startmaster09

error in /www/var/sync/startmasterXX from 09...12 - executable flag is missing.

solution:  
$ cd /www/var/sync
$ sudo chmod +x startmaster09 
repeat for 10…12 then GET... is working! 

solution for osc not working
mapped osc incoming messages via puredata to tcp-commands like GET... to localhost

@magdesign: ever thought of integrating puredata to pocketvj?

**Comment by magdesign** [comment]
Thanks for the hint. Fixed it.
You can always click "Factory Preset" to fix errors like this.

Puredata looks interesting.. maybe I will find some time once to integrate this as well

**Comment by zimtzeke** [comment]
@magdesign: write me when you decide to integrate puredata. i would support this.

**Comment by magdesign** [comment]
Ok. I am just integrating PureData.
Here is a tutorial on how to install when you have PVJ 3.7 or oder:
https://github.com/magdesign/PocketVJ-CP-v3/blob/master/PureData_install.md

**Comment by zimtzeke** [comment]
hi,
wow. you're fast. i read the installer and changes to backend.php plus startpd in ../sync. good thing!
in my opinion the true power of pd in combination with pocketvj on pi lies in running it without the gui to do some audio- or live-input- (sensors/whatever) or datamapping- (osc-to-pjlink-to-rs232-to-midi-to-whatever) processing in the background and pass it over to pvj's interface. 
as the v0.43 is still on the pd-website but quite outdated i'll be back to you soon.
yours.

**Comment by magdesign** [comment]
you can run it without gui with: /usr/bin/pd-extended -nogui

I think the gui is useful for writing the code, as soon as we have some code (e.g. midi to cmd) I can integrate functions to run puredata in background.
