### ISSUE TITLE
fsaysuidev

### ISSUE THREAD

**Issue by kermit60fr** [magdesign/PocketVJ-CP-v3#73]
hello, who could give me an example of the file fsaysuidev because the http://www.fsays.eu/Blogging/Blog/Details/23 does not work anymore

thanks, sorry for my english google translation

**Comment by magdesign** [comment]
https://github.com/magdesign/PocketVJ-CP-v3/issues/3#issuecomment-223814712

**Comment by kermit60fr** [comment]
thank you
another small question, the mouse does not work in the map? even in the branch
