### ISSUE TITLE
Resolution 1680x1050

### ISSUE THREAD

**Issue by bereza0007** [magdesign/PocketVJ-CP-v3#75]
When I click 1680 x 1050 in CP , on text window on top displays " force 1920x1200 rgb". All functionality working, just message wrong, I think.

**Comment by magdesign** [comment]
Thanks!
Just fixed it:
https://github.com/magdesign/PocketVJ-CP-v3/blob/b57f77635438f866b65dc0482ad87beae4bd5d13/backend.php#L781
