### ISSUE TITLE
gstreamer0.10-plugins-bad is not available

### ISSUE THREAD

**Issue by mshaub** [magdesign/PocketVJ-CP-v3#77]
I am trying to build from scratch. When attempting to install all required packages I got an error "gstreamer0.10-plugins-bad is not available." This is on a fresh install of the 2018-11-13-raspbian-stretch-full image. Is there a replacement for this package? Are these plugins now included in an updated gstreamer version? Thanks!

**Comment by magdesign** [comment]
The gstreamer plugins are only used for the webRTC audio transmission. The rest should work without them.

My build is still based on Debian Jessie.
You might try it with backports if you need the desired function.
