### ISSUE TITLE
Max Bitrate

### ISSUE THREAD

**Issue by pramodmadhav** [magdesign/PocketVJ-CP-v3#79]
With 2k HD video what is the max bit rate (MBPS) of the video file that can be played.
If I want to play video file of 40 MBPS is it possible?

**Comment by magdesign** [comment]
The maximum video resolution of PocketVJ is FullHD (1920x1080).

For syncing purposes I would go for a bitrate between 10 -15 mb/s for video and 160kbit for audio.
I think its possible to run up to a bitrate of 40 mb/s, but for syncing you would have to change the sync offset in the omxplayer-sync script.

**Comment by pramodmadhav** [comment]
many thanks will try and let you know though its too late now will try for another project
