### ISSUE TITLE
Build from scratch - Guide for n00bs

### ISSUE THREAD

**Issue by slagteriet** [magdesign/PocketVJ-CP-v3#80]
Hi @magdesign  
I have known about your project for a while, but never got the time trying it myself until now.

I know about a lot of companies here who are using your pocketVJ for business installations, thumbs up.

As I was trying to compile a project for testing old tv screens I followed your guide and @baydam's guide. 

Im kindda close to something. but ran into a couple questions.

I added latest version of eXtplorer 2.1.12 and OMXplayer 0.3.7 version below.

wget http://extplorer.net/attachments/download/78/eXtplorer_2.1.12.zip

and latest version of OMXplayer for raspberry same [one here](https://github.com/turingmachine/omxplayer-sync)

wget https://omxplayer.sconde.net/builds/omxplayer_0.3.7~git20170130~62fb580_armhf.deb

I can start the PocketVJ Control Panel , but it won't play anything an eXtplorer is just blank..?

Rearding TCPSclient here is what I used for RPI3 with stretch [link here](https://github.com/z37soft/INetSyphon_RaspberryPi_SDK)

These steps won't install in the fist dependencies you have to install..
gstreamer1.0
gstreamer0.10-plugins-bad
firmware-ralink

I hope you would give a short advise on this...

**Comment by magdesign** [comment]
Its all about the right configuration.
check the eXtplorer docs and this: https://github.com/magdesign/PocketVJ-CP-v3/issues/68

**Comment by slagteriet** [comment]
Thank you @magdesign 
I got the player working buy following this guide from [openFrameworks](https://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/)

Will try setup the eXtplorer from the guide you just posted. Thanks a lot.

**Comment by slagteriet** [comment]
@magdesign the solution on the eXtplorer is to install [PHP7.0-xml](ttps://packages.debian.org/search?keywords=php7.0-xml)
and [php7.0-mbstring ](https://packages.debian.org/stretch/php7.0-mbstring)

sudo apt-get install php7.0-xml php7.0-mbstring
sudo service lighttpd restart

**Comment by DEKAGATO** [comment]
Hi @magdesign I have small question hope you can help (sorry cuz I'm completely noob with rasberry pi) 
i already install pocket vj on raspberry pi and pc connect it as well but i run it on rasbian full (not a lite version) so how can i run project as start up. Thankyou alot
