### ISSUE TITLE
WLAN Control / 7x PocketVJ / change WLAN IP

### ISSUE THREAD

**Issue by cosmos525** [magdesign/PocketVJ-CP-v3#85]
Hey there, 
I‘m new to github an Pocket VJ. 

We are planning a Project with 7 pocketVJ Devices. 
We like to trigger them with OSC commands or TCP via WLAN.

Rightnow we have one device to check if it could be 
Later I like to set them to divverend IP adresses to join one Wlan.
They are delivered with fixed WLan IP.
In the web interface  I searched for he option  to change the IP adresse for the WLAN, but didnt find. Just for the ethernet port. 

How can I do that? 
Thank you for your Suggestions & Ideas. And maybe some experiences with such wireless  
( we have no possibility for cabling)

**Comment by magdesign** [comment]
There is no function in CP to change the Wifi IP.

I think best solution for connecting 7 PocketVJs would be by setting up a WIFI router for only the PocketVJ network, and change the PocketVJ from Hotspot mode to connect to your Wifi network.

**Comment by cosmos525** [comment]
Thank you. 
Can you give me a hint, how to do this?
Where can I change the Wifi mode?

**Comment by magdesign** [comment]
in /etc/network/interfaces
change it to something like this: 
https://github.com/magdesign/PocketVJ-CP-v3/blob/master/sync/interfaceswifi

backup the original file first....

**Comment by GabrioGi** [comment]
> in /etc/network/interfaces
> change it to something like this:
> https://github.com/magdesign/PocketVJ-CP-v3/blob/master/sync/interfaceswifi
> 
> backup the original file first....

Where should I place, or found, that file on my raspberry?
Is there a way to change this settings from the raspberry terminal?
I need to connect the pocketvj to Internet through the wifi because the ethernet is used to control the Projector.
Thanks
Gabrio

EDIT:
I've found the file in var/www/sync but editing it with my SSID and Password, nothing happens.
When I click on "WiFi ON" in the browser the pocketvj appear to be in AP mode because I see the vj100 wifi network

**Comment by Electroman1000** [comment]
How do I connect 5 Pocketvjs to wireless router? They sync fine via Ethernet to the router. Router is only connected to laptop and pocketVJ’s only local network, no internet needed. I have version 3.7, CP 2.5.0

**Comment by magdesign** [comment]
Make sure your router is set to 192.168.2.1
Then connect your PocketVJs via RJ45 cable.

**Comment by Electroman1000** [comment]
Yes that works perfectly, but I would rather connect VJ’s via WiFi to the router

**Comment by magdesign** [comment]
This is not a simple task.
You need to configure quite a lot of stuff in the system, its not officially supported on PocketVJ RTC.

**Comment by Electroman1000** [comment]
Ok thanks for the quick response
