### ISSUE TITLE
In mapping mode videos doesn't play well

### ISSUE THREAD

**Issue by GabrioGi** [magdesign/PocketVJ-CP-v3#86]
I'm trying to do a video mapping.
I've only one surface with a geometrical deformation. When I select the vj video sample, this plays jerky and if I select one of my mp4 they doesn't appear in the surface and all appear black.
Moreover it's not clear, after the exported of a mapping settings, what should I do to start the vj with that configuration.
Enabling the "VIDEOPLAYER as MASTER" doesn't load the mapping settings
Should the pocketvj start always in MAPPING Mode?

**Comment by magdesign** [comment]
How is your video encoded?
h264, mp4, 10mbit/s, 1280x720 pixel do work best.
How is your video named?
Do not use any special characters and whitespaces.
Which testvideo is jerky?
If you test it with the man walking along the screen, it should run smooth. If you use the fullhd one, it will take a moment until it runs smooth.
If you want to "Autostart" in to mapping, you need to select this in the CP.

Please do not ask several questions in one issue, its better to open an issue for every question.

Check out the tutorials: https://pocketvj.com/#Tutorials
and the manual: https://pocketvj.com/pdf/manual3.pdf

**Comment by GabrioGi** [comment]
The video is encoded with:
H.264 1280x720 1,24Mbit/s 
AAC 48000Hz
filesize 2.1 Mb
Duration: 12 sec.
Filename: 01_SampleVideo_1280x720_2mb.mp4 (no spaces, only "_" )
In VIDEOMODE my video plays correctly.

The test video that is jerky is "PVJ_Testvideo201.mp4" also after 2 play till the end

The man walking run smooth also to me.

**Comment by magdesign** [comment]
Try to make the video longer, at least 40 seconds.
Try to make the name shorter: e.g. "sample_720.mp4"

**Comment by GabrioGi** [comment]
with another video it plays smooth, but often in Mapping mode, when I'm connected to the wifi, the pocketvj reboots.
So it's a little bit difficult to do the mapping

**Comment by magdesign** [comment]
When you hit reboot in the CP, you have to close the browser tab where the CP is opened, otherwise the browser will send the last command when the wifi is up again and you get a boot loop.

I am aware of this, but could not figure out a solution yet...

**Comment by GabrioGi** [comment]
nice, thanks a lots.
