### ISSUE TITLE
no audio in wifi-sync mode

### ISSUE THREAD

**Issue by mandelbrotmedia** [magdesign/PocketVJ-CP-v3#87]
Hi,

it seems like there is no audio in wifi-sync mode.
on the master there is audio. 
on the slave not. 
when playing the slave RPI in standalone mode there is audio. so i think this is not a codec issue.

please help :-)

**Comment by magdesign** [comment]
Wifi sync is still beta, thanks for the bug report, I will take a look at it...

**Comment by magdesign** [comment]
this will not be fixed, its out of scope for the moment, so closing issue.
