### ISSUE TITLE
how to donate ?

### ISSUE THREAD

**Issue by earsneyes** [magdesign/PocketVJ-CP-v3#88]
Halloween is coming, myself and my boy can't wait to put our halloween mapping installation in place. Thanks for the great work on pocketvj!
I am asking myself how can i send a few bucks for a beer or such ?

**Comment by magdesign** [comment]
Hi
Thanks for using PocketVJ.
Since its still not possible in the year 2019 to push a Gin Tonic through the internet, here a donation link: 

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=D4Q98LZF9UZE6&source=url

**Comment by earsneyes** [comment]
ok great stuff, keep up the good work! been enjoying it everytime i pick it up! Cheers

**Comment by magdesign** [comment]
Thank you very much for the donation :-)
