### ISSUE TITLE
PocketVJ on RPi 4 (4GB)

### ISSUE THREAD

**Issue by earsneyes** [magdesign/PocketVJ-CP-v3#89]
Since the Raspberry Pi4 is released i am keen to migrate to newer hardware.
Anybody tried a RaspberryPi 4 ? Are there benefits over using a RPI3 B+ ?
I am looking for the best performance. 
Maybe UHD resolution / h265 compatibility ?

Regards
Linus

**Comment by magdesign** [comment]
I tried it and have to say that it does not make sense, the HW support for graphics is bad and I hate the mini HDMI plugs. As long as there is no better hardware support I will not upgrade the project to RPi4.

**Comment by earsneyes** [comment]
ok then i will stick with the RPI3's i have for now. Thanks!

**Comment by DambronOlivier** [comment]
> I tried it and have to say that it does not make sense, the HW support for graphics is bad and I hate the mini HDMI plugs. As long as there is no better hardware support I will not upgrade the project to RPi4.

hi @magdesign ,amazing work and thanks so much for sharing.
 any chance the hardware support improved? the mini hdmi are not that bad.
 Could you reconsider updating the projec for Rpi4 ? :)

**Comment by magdesign** [comment]
Due various reasons I am still not planning to port to Rpi4 (e.g. openframeworks support, overheating issues, gpu driver, supply shortage, still enough units/cases in stock).

Rpi3 is still available on the market and everything runs completely fine.
I am more interested in optimizing the software than buy new hardware. 

You are welcome to port to Rpi4 and contribute ;-)

**Comment by DambronOlivier** [comment]
fair enough mate, thanks for your reply.
I'll go with RPI3.

I wouldn't know myself how to port to RPI4, as of now.

All the best
