### ISSUE TITLE
Can't sync video over wifi 

### ISSUE THREAD

**Issue by Electroman1000** [magdesign/PocketVJ-CP-v3#90]

**Comment by magdesign** [comment]
Without a description is this issue useless...

Read the manual on page 9:
https://pocketvj.com/#Downloads

and exactly write where the error occurs.

**Comment by Electroman1000** [comment]
Can I change the WiFi IP of the second VJ? Both are 2.0.0.100
Also both have the same WiFi name VJ100 so I have to power off one to connect to the other. 
Is it because I have version 3.7, CP 2.5.0?

**Comment by magdesign** [comment]
https://github.com/magdesign/PocketVJ-CP-v3/issues/85
