### ISSUE TITLE
Mapping mode doesn't work

### ISSUE THREAD

**Issue by romaincollinet** [magdesign/PocketVJ-CP-v3#92]
Hi !

I update all the component this morning and now the mapping Mode dont work. When i clic open show, it load but when i clic mapping mode nothing happen. 

My vidéo file is an mp4 H264, 19020 x 1080.

I can not either access mapping mode with your examples show.

Have you ever seen this probleme and have you the miracle solution ?

Thank's by advance

Romain

**Comment by magdesign** [comment]
Which CP Version do you have?
Did you refresh the browser?
USB Mouse connected?

**Comment by romaincollinet** [comment]
I get the last version on pocketvj.com but it 2.5.1 on the to right

**Comment by romaincollinet** [comment]
And yes and yes.

**Comment by romaincollinet** [comment]
I saw i previous post with the same probleme and i update everyting a second time but still the same

**Comment by magdesign** [comment]
Also tried autostart to mapping mode?

**Comment by magdesign** [comment]
Will make a test today to figure out whats going on....

**Comment by romaincollinet** [comment]
Thank's

**Comment by romaincollinet** [comment]
Yes an id, I saw in the Releas notes it's the 3.9 but whent it start it 3.5 on the start screen.

**Comment by romaincollinet** [comment]
I have do update another time and  i have this message when i load mapping show :


[notice ] ofAppEGLWindow: setupRPiNativeWindow(): screenRect: 1920x1080 [notice ] ofAppEGLWindow: setupRPiNativeWindow(): windowRect: 1024x768 [notice ] ofAppEGLWindow: createSurface(): setting up EGL Display [notice ] ofAppEGLWindow: createSurface(): EGL Display correctly set 0x1 [notice ] ofAppEGLWindow: createSurface(): no current renderer selected [notice ] ofAppEGLWindow: createSurface(): default renderer detected [notice ] ofAppEGLWindow: createSurface(): surface created correctly [notice ] ofAppEGLWindow: createSurface(): API bound correctly [notice ] ofAppEGLWindow: createSurface(): -----EGL----- [notice ] ofAppEGLWindow: createSurface(): EGL_VERSION_MAJOR = 1 [notice ] ofAppEGLWindow: createSurface(): EGL_VERSION_MINOR = 4 [notice ] ofAppEGLWindow: createSurface(): EGL_CLIENT_APIS = OpenGL_ES OpenVG [notice ] ofAppEGLWindow: createSurface(): EGL_VENDOR = Broadcom [notice ] ofAppEGLWindow: createSurface(): EGL_VERSION = 1.4 [notice ] ofAppEGLWindow: createSurface(): EGL_EXTENSIONS = EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_vg_parent_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_lock_surface [notice ] ofAppEGLWindow: createSurface(): GL_RENDERER = VideoCore IV HW [notice ] ofAppEGLWindow: createSurface(): GL_VERSION = OpenGL ES-CM 1.1 [notice ] ofAppEGLWindow: createSurface(): GL_VENDOR = Broadcom [notice ] ofAppEGLWindow: createSurface(): ------------- [notice ] ofAppEGLWindow: setupPeripherals(): peripheral setup complete [notice ] ofAppEGLWindow: setupNativeUDev(): created udev object [notice ] ofAppEGLWindow: setupMouse(): mouse_fd= 5 devicePath=/dev/input/by-path/platform-3f980000.usb-usb-0:1.2:1.0-event-mouse [notice ] ofAppEGLWindow: setupMouse(): mouse device name = PIXART USB OPTICAL MOUSE [warning] ofAppEGLWindow: setupKeyboard(): unabled to find keyboard [notice ] ofAppEGLWindow: setupPeripherals(): native event setup complete [notice ] Got device [notice ] node: %s [notice ] subsystem: %s [notice ] devtype: %s [notice ] action: %s [warning] ofFile: copyTo(): destination file "../../home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/videos/AO_FUNDAZTION_2.mp4" already exists, set bool overwrite to true if you want to overwrite it [warning] ofFile: copyTo(): destination file "../../home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/videos/Montage.mp4" already exists, set bool overwrite to true if you want to overwrite it [warning] ofFile: copyTo(): destination file "../../home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/images/01_PocketVJ.jpg" already exists, set bool overwrite to true if you want to overwrite it [warning] ofFile: copyTo(): destination file "../../home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/images/02_PocketVJ.jpg" already exists, set bool overwrite to true if you want to overwrite it [warning] ofFile: copyTo(): destination file "../../home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/images/Convention-Saur-.jpg" already exists, set bool overwrite to true if you want to overwrite it [warning] ofFile: copyTo(): destination file "../../home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/images/Convention-Saur-Mucem-Video-Events-2.jpg" already exists, set bool overwrite to true if you want to overwrite it [warning] ofFile: copyTo(): destination file "../../home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/images/Mask.png" already exists, set bool overwrite to true if you want to overwrite it [warning] ofFile: copyTo(): destination file "../../home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/images/Model_B&W.png" already exists, set bool overwrite to true if you want to overwrite it [warning] ofFile: copyTo(): destination file "../../home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/images/black.jpg" already exists, set bool overwrite to true if you want to overwrite it [warning] ofFile: copyTo(): destination file "../../home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/images/overlay.png" already exists, set bool overwrite to true if you want to overwrite it [notice ] MediaServer: Attempting to add FBO source with name Cross FBO Source [notice ] MediaServer: Source new, adding [notice ] MediaServer: Attempting to add FBO source with name FBO Source [notice ] MediaServer: Source new, adding [notice ] MediaServer: Attempting to add FBO source with name Slide Show Source [notice ] MediaServer: Source new, adding numPresets: 1 [notice ] MediaServer: Initialized reference count of /media/internal/images/02_PocketVJ.jpg to 1 [notice ] MediaServer: Initialized reference count of /media/internal/images/01_PocketVJ.jpg to 1 [verbose] 02_PocketVJ.jpg [verbose] overlay.png [verbose] Convention-Saur-Mucem-Video-Events-2.jpg [verbose] 01_PocketVJ.jpg [verbose] Mask.png [verbose] Convention-Saur-.jpg [verbose] black.jpg [verbose] Model_B&W.png [verbose] listed 8 files in "/media/internal/images/" [verbose] 02_PocketVJ.jpg [verbose] overlay.png [verbose] Convention-Saur-Mucem-Video-Events-2.jpg [verbose] 01_PocketVJ.jpg [verbose] Mask.png [verbose] Convention-Saur-.jpg [verbose] black.jpg [verbose] Model_B&W.png [verbose] listed 8 files in "sources/images/" [verbose] 02_PocketVJ.jpg [verbose] overlay.png [verbose] Convention-Saur-Mucem-Video-Events-2.jpg [verbose] 01_PocketVJ.jpg [verbose] Mask.png [verbose] Convention-Saur-.jpg [verbose] black.jpg [verbose] Model_B&W.png [verbose] listed 8 files in "/media/internal/images/" [verbose] 02_PocketVJ.jpg [verbose] overlay.png [verbose] Convention-Saur-Mucem-Video-Events-2.jpg [verbose] 01_PocketVJ.jpg [verbose] Mask.png [verbose] Convention-Saur-.jpg [verbose] black.jpg [verbose] Model_B&W.png [verbose] listed 8 files in "sources/images/" [verbose] 02_PocketVJ.jpg [verbose] overlay.png [verbose] Convention-Saur-Mucem-Video-Events-2.jpg [verbose] 01_PocketVJ.jpg [verbose] Mask.png [verbose] Convention-Saur-.jpg [verbose] black.jpg [verbose] Model_B&W.png [verbose] listed 8 files in "/media/internal/images/" [verbose] 02_PocketVJ.jpg [verbose] overlay.png [verbose] Convention-Saur-Mucem-Video-Events-2.jpg [verbose] 01_PocketVJ.jpg [verbose] Mask.png [verbose] Convention-Saur-.jpg [verbose] black.jpg [verbose] Model_B&W.png [verbose] listed 8 files in "sources/images/" [verbose] 02_PocketVJ.jpg [verbose] overlay.png [verbose] Convention-Saur-Mucem-Video-Events-2.jpg [verbose] 01_PocketVJ.jpg [verbose] Mask.png [verbose] Convention-Saur-.jpg [verbose] black.jpg [verbose] Model_B&W.png [verbose] listed 8 files in "/media/internal/images/" [verbose] 02_PocketVJ.jpg [verbose] overlay.png [verbose] Convention-Saur-Mucem-Video-Events-2.jpg [verbose] 01_PocketVJ.jpg [verbose] Mask.png [verbose] Convention-Saur-.jpg [verbose] black.jpg [verbose] Model_B&W.png [verbose] listed 8 files in "sources/images/" [verbose] 02_PocketVJ.jpg [verbose] overlay.png [verbose] Convention-Saur-Mucem-Video-Events-2.jpg [verbose] 01_PocketVJ.jpg [verbose] Mask.png [verbose] Convention-Saur-.jpg [verbose] black.jpg [verbose] Model_B&W.png [verbose] listed 8 files in "/media/internal/images/" [verbose] 02_PocketVJ.jpg [verbose] overlay.png [verbose] Convention-Saur-Mucem-Video-Events-2.jpg [verbose] 01_PocketVJ.jpg [verbose] Mask.png [verbose] Convention-Saur-.jpg [verbose] black.jpg [verbose] Model_B&W.png [verbose] listed 8 files in "sources/images/" PiMapper launched
--

**Comment by magdesign** [comment]
You seem to have PocketVJ 3.5, with CP 2.5.1

I just made an Update to CP 2.5.1 on an older image and here it works.
Can you please describe me in clear words what exactly is not working?

1.) Autostart to mapping mode
2.) Connect USB mouse
3.) Reboot PocketVJ
4.) When PocketVJ is up and running, click mouse, you should see the edges of every surface
5.) In CP you are now able to click 1. MAPPING Mode 2.Add Quad 3.Media Stepper
and you should see all your medias.

**Comment by romaincollinet** [comment]
when i clic mapping mode on web brother interface i see mapping mode writing like it do the thing and i see led on the PI flashing but do nothing.

and I try all you conseil me but not working, i re dowload from github update and still the same.

I make an image from the sd card download it and ...



It's on my personal server it coud take some time.

Thank's

**Comment by magdesign** [comment]
Please do not upload images of the PocketVJ to the internet, and please remove the link!
It would be much more useful if you would make a video of what you are doing and what is not working.

Do you have a cabled usb mouse connected?
Did you try to click: "Update Mapper" in Control Panel?

Did you try this tutorial: https://vimeo.com/185559286

**Comment by romaincollinet** [comment]
Sorry, it's done, i remove it.

Yes i do the tutorial a years ago when i start with poketvj and i work with for different exibitions. But after updating mapping mode is not working.

Yes I have mouse connected and I update mapper, mapper audio, video sync perfomence, ...

**Comment by magdesign** [comment]
Can you connect a usb keyboard to the PocketVJ and try if it is working with the keyboard.

The keyboard commands are here (scroll down a bit):
https://github.com/magdesign/ofxPiMapper

**Comment by magdesign** [comment]
Can you also try all of the predefined mappersets to check if one is working...

**Comment by romaincollinet** [comment]
I go to Davos today to worck. I'll do more tests when i'll come back.

Thank's for your reactivity and patience.

**Comment by magdesign** [comment]
If it still does not work and you are based on switzerland, contact me via email.

**Comment by romaincollinet** [comment]
I'm not base on switzerland, I'm from Marseille. I come to work. I'm back the first decembre.

**Comment by magdesign** [comment]
I just figured out that there is an issue when using a wireless usb mouse... 
it works with a generic usb cable mouse.... 

If you use a wifi/bluetooth mouse, the mapper thinks there is also a wifi keyboard connected to the wifi receiver and tries to load this instead of the fake usb keyboard i generate.

With a cable usb mouse, we get:
```
/dev/input/event0:	Logitech USB Optical Mouse
/dev/input/event1:	uinput-fsays

```
With a wireless mouse, we get:
```
/dev/input/event0:	Logitech USB Receiver
/dev/input/event1:	Logitech USB Receiver
/dev/input/event2:	uinput-fsays
```

So I am trying to forward `/dev/input/event2` to `/dev/input/event1`
or delete event1 and force uinput-fsays to event1,
after 5h testing without success, I am giving up for the moment.
If anyone has experience in this, write me.

The thing is that Openframeworks does not seem to support multi keyboard entries.
https://forum.openframeworks.cc/t/hotplug-multiple-keyboard-support/22672/5

**Current workarounds:**
**- use a cabled usb mouse (after boot you can unplug and plugin your wifi mouse)**
**- use an usb keyboard to type commands (e.g. "d" for delete etc.)**

**Comment by romaincollinet** [comment]
I'm sorry for thé delay. Work !

I test with keyboard shortcut and it's working. But not Moïse. (Cable)

**Comment by magdesign** [comment]
Did you read updated post above...

**Comment by romaincollinet** [comment]
yes and i only use cable mouse on PI.


Romain Collinet
3 rue Plumier
13002 Marseille

+33(0) 6 15 55 78 54



http://airsolid-design.com/
https://vimeo.com/airsoliddesign

**Comment by romaincollinet** [comment]
for now i can't do test because the pi is to davos for a project and i'm
back to Marseille. I get it bac the 15 december.


Romain Collinet
3 rue Plumier
13002 Marseille

+33(0) 6 15 55 78 54



http://airsolid-design.com/
https://vimeo.com/airsoliddesign


Le mer. 11 déc. 2019 à 12:30, Romain collinet <collinet.romain@gmail.com> a
écrit :

**Comment by BjarneJensen** [comment]
Hey I am not sure if you ever solved the mouse issue, but I was able to get it working with the following commands. Probably not the most elegant solution.

(if no mouse)
`ln -s /dev/input/event0 /dev/input/event1`    _//link fsays to event 1_
(if wireless mouse is present)
`mv /dev/input/event1 /dev/input/event7`       
`ln -s -f /dev/input/event0 /dev/input/event1`  _//move mouse to empty event & link fsays to event 1_
(revert to mouse)
`ln -s -f /dev/input/event7 /dev/input/event1`  _//force link mouse back to event 1_

You might have to adjust some settings depending on your configuration. Let me know if this helps.

BJ

**Comment by romaincollinet** [comment]
I'll find a way last time.

But it's a long time ago and I do not remember.

Thank's for your reply !

have a good day


Romain Collinet
3 rue Plumier
13002 Marseille

+33(0) 6 15 55 78 54



http://airsolid-design.com/
https://vimeo.com/airsoliddesign


Le dim. 28 févr. 2021 à 23:02, BjarneJensen <notifications@github.com> a
écrit :

**Comment by romaincollinet** [comment]
Hi !

Could you send me a link to reload poketVj. 

My sd-card dont boot !

I just have black screen.

Thank's by advance

**Comment by romaincollinet** [comment]
Hi !

I have a problem with my PoketVj SD card back up. It doesn't boot, I just
have a black screen. Is it possible for you to give me a link to reload it ?

I Use it many times and I really need it at this moment.

Thanks by advance

Romain Collinet


AirSolid- design
37 rue Guibal
13003 Marseille

+33(0) 6 15 55 78 54



http://airsolid-design.com/
https://vimeo.com/airsoliddesign


Le lun. 1 mars 2021 à 08:08, Romain collinet ***@***.***> a
écrit :

**Comment by magdesign** [comment]
the link is in the about page on pocketvj.com

**Comment by romaincollinet** [comment]
Hi !

Thank's for your response.

I've try to burn the img.xz file, with Raspberry Pi imager and at each time
I have this message :

Extraction error : Lzma library error: No progress is possible.

[image: Capture.PNG]

I've try to uncompress it and burn it and with PI imager, he say it's not a
valid file because it's not a multiple of 512 bit.
With win32 diskimager and balenaEtsher, he burn it, but at boot of Rpi,
green LED flash 3 time and the red and green shutdown. I have message on
screen :

Failed to insert module 'ipv6'
Filebrowser .service lacks both ExecStart= and ExecStop= setting. Refusing.

I think the source file may be damaged. I download tree time to be sure

Do you know what can I do?

Thank's for all by advance

Romain Collinet


AirSolid- design
37 rue Guibal
13003 Marseille

+33(0) 6 15 55 78 54



http://airsolid-design.com/
https://vimeo.com/airsoliddesign
