### ISSUE TITLE
Build from scratch Raspberry 3B+

### ISSUE THREAD

**Issue by WhereIsLucas** [magdesign/PocketVJ-CP-v3#93]
Hello, 

First of all, thanks for this cool project! 

I'm trying to build pocketvj from scratch. I tried with Buster and stretch, but I can't get to the end of the process, but I think I'm close to something.
I'm following the guide on the README file and this one : https://gist.github.com/baydam/a905e4878f54150f7da421e2c1d17a21 

I want to give it a spin with Jessie, but I don't find any resources about installing Jessie on the 3B+. I tried as proposed here : https://github.com/magdesign/PocketVJ-CP-v3/issues/53#issuecomment-464145622 , but my keyboard is not working. 

Thanks for your help!

**Comment by magdesign** [comment]
Use the Raspian Jessie Lite image.

To have remote access via Control Panel (for mapping and presentation) you must simulate a fake keyboard, see here: http://www.fsays.eu/Blogging/Blog/Details/23 (place it in /opt/fsaysuinput /opt/fsayskeyboard)

**Comment by WhereIsLucas** [comment]
Thanks for your answer! 
I can't get any working Jessie Lite image for the 3B+, as jessie doesn't have the correct firmware for the 3b+, where should I search for ?

Edit: I don't have a Pi 3 (not +) to prepare the SD card as proposed in the majority responses I found in forums.

**Comment by magdesign** [comment]
I have no idea....
maybe someone who built one from scratch can help here.

**Comment by WhereIsLucas** [comment]
I'll search and if I find something, I'll keep this issue updated for future reference.
Thanks for your help and for this cool project!

**Comment by WhereIsLucas** [comment]
@magdesign what version of the raspberry would you recommend using? I'm planning to buy another one and I'll be glad to run PocketVJ on it.
Thanks!

**Comment by magdesign** [comment]
Raspberry 3B+

**Comment by BjarneJensen** [comment]
@WhereIsLucas did you ever get it working? I was able to set it up a few days ago on Raspi 3b with Jessie, but it broke when I tried to update through the menu. I reflashed and Haven't been able to get through the whole build process since. I should have gotten a log of all my commands before reflashing. I'll report back if I get it right. Thanks

**Comment by WhereIsLucas** [comment]
Hi,
No I wasn't able to get it working, sadly. I finally used another tool (https://ofxpimapper.com/). It was a PITA to be fair, and I resigned. Maybe I'll give it a new try when I'll get a new Pi 3B+ and report back too.

**Comment by BjarneJensen** [comment]
I guess the problem was that I put the card back into the wrong pi (3b+), when I had built it on a 3b. I was able to get it working on both by updating from the older pi. I think I initially had problems installing qlc, so I had to build from source.

**Comment by ChrisWoll** [comment]
Hi, did anyone get it up and running on a RPi 3B+ yet? 
If yes, could the person maybe upload the steps or an img of the SD card?

Thank you very much!

**Comment by magdesign** [comment]
find the hidden tressure, read the about page on pocketvj
&
be nice and be the first one who makes a donation.
