### ISSUE TITLE
Connection Lost while connected to the wifi

### ISSUE THREAD

**Issue by TrigFardust** [magdesign/PocketVJ-CP-v3#94]
![reconnect](https://user-images.githubusercontent.com/72168630/94743011-f36d8f80-0376-11eb-9952-6d769d10d954.jpg)
I cant work in the menu anymore. Because the connetion to the pocketvj is not working, i get the dialogtext: "Connection Lost.  Reconnecting in 1 minute". When i press the Reconnect Button - nothing happens. The Wifi Connection is still working, but need very long to connect in the begining of the session. I have more then one poket vj - the other 2 work properly. What can i do? Thanks for Help.

**Comment by magdesign** [comment]
If you have several PocketVJ's in an installation, it can be that the wifi-frequencies are working against each other.
To solve this, go to the red "System" tab, scroll down to "Wifi", select a different channel than "CH6" and reboot.
if you ordered several PocketVJ's together, I might have already changed the "CH" settings. Its known that MacBooks have problems with certain frequencies. In this case, set the wifi channel to "CH6" and try again.

This might solve the issue!

Others:
- Delete the browser cache
- Use Chrome browser

**Comment by TrigFardust** [comment]
I try this - but i used only one in the test i did.
Hope this solves the problem.
Thank you for the response
Hugs Claude


Am 2020-10-01 10:01, schrieb magdesign:

**Comment by TrigFardust** [comment]
I try to get the connection to the Pocket Vj - but it doesent get it. I erase the browser cache and unplug any usb stick - but i cant reach the pocket vj and therefore i cant reboot the system and cant change the channel. What can i do now? I need to load a movie.

**Comment by TrigFardust** [comment]
HELP !!!
After all it becomes worse! I use 3 different PocketVJ but just single (2 are working fine). The one i get trouble since days becomes a problem child. I dont know what to do now. As i cant get any connection anymore! I used the newest Google Chrome Browser and the Wifi works - but need now 5 minutes to connect. I need help - because i have to load a movie and install it latestly monday. Can i make a direct connection by ethernet cable?
![noconnection](https://user-images.githubusercontent.com/72168630/94901623-34f55c00-0497-11eb-89de-eb51c4de4c30.jpg)

**Comment by magdesign** [comment]
I can send you a warranty replacement since I have no idea what is wrong on this unit, I feel sorry, please  contact me via email!

Yes, you can direct connect via LAN cable.
Connect the cable from your Macbook to the PocketVJ directly,
in the osx network settings change to manual IP, choose something like; 192.168.2.200
subnet 255.255.255.0  (see this video https://vimeo.com/375876811 from 0:55 to 1:29)
Then you can access your PocketVJ with 192.168.2.101

hope that helps.

**Comment by TrigFardust** [comment]
Dear Marc - thanks for your fast feedback! I will try a direct ethernet connection, but maybe its better to change the ocketVJ for another one - because i need the wifi connection when its installed. I finish the installation mid of october - maybe i send you this Pocket VJ back, and will become another one...

**Comment by magdesign** [comment]
Found the issue:
When in Control Panel selecting Wifi CH1 the frequency is too low for e.g. apple computers, do not use CH1, use higher numbers like CH11 CH6 CH9

and still, there are some units which have a broken wifi chip and will be warranty replaced.

**Comment by magdesign** [comment]
see also here:
https://github.com/magdesign/PocketVJ-CP-v3/issues/38
