### ISSUE TITLE
Missing/Outdated info in Build from Scratch Instructions

### ISSUE THREAD

**Issue by andyrblank** [magdesign/PocketVJ-CP-v3#95]
I have downloaded **2017-07-05-raspbian-jessie-lite** and I'm going through the instructions to build from scratch but I've run into these issues.

all php packages are now php5 in Jessie and libcppunit-1.13-0v5 is libcppunit-1.13-0 (libcppunit-1.13-0v5 comes back as not found)

`sudo apt-get -y install avahi-daemon avahi-utils dosfstools exfat-fuse exfat-utils expect expect-dev fbi feh figlet firmware-ralink git-core gparted hfsplus hfsprogs hfsutils hostapd iceweasel imagemagick iptables isc-dhcp-server libao-dev libavahi-compat-libdnssd-dev libavahi-compat-libdnssd-dev libgstreamer-plugins-base0.10-dev libgstreamer-plugins-base1.0-dev libgstreamer0.10-0 libgstreamer0.10-dev libjpeg8 libjpeg8-dev libncurses5-dev libopenblas-dev libreoffice-impress libva-dev lightdm lighttpd lxappearance lxde-core lxterminal mediainfo mpg123 mpg321 ntfs-3g okular php5 php5-cgi php5-cli php5-common php5-mysql python-dbus python-dev python-pexpect python-pip python-smbus rc-gui samba samba-common-bin screen shellinabox tk ttf-mscorefonts-installer usbmount vim x11-xserver-utils xdotool xinit xpdf xtightvncviewer youtube-dl gstreamer0.10-plugins-base gstreamer0.10-plugins-good gstreamer0.10-tools gstreamer0.10-plugins-ugly gstreamer0.10-plugins-bad gstreamer1.0 subversion libfreeimage3 libcppunit-1.13-0 libcppunit-dev ola ola-python g++ make git build-essential libqt4-dev qt4-dev-tools fakeroot debhelper devscripts pkg-config libasound2-dev libusb-dev libftdi-dev libudev-dev libmad0-dev libsndfile1-dev libfftw3-dev`

The dependencies above need to be installed before you can run `sudo lighty-enable-mod fastcgi-php`

pip needs to be updated before the instruction `sudo pip install pjlink python-osc svgtools svgpathtools svgwrite PyYAML evdev` is run by using: `sudo pip install --upgrade pip` and `sudo pip install --upgrade setuptools`

cython is required `sudo pip install cython`

**QLC+**
_source: https://github.com/mcallegari/qlcplus/wiki/Linux-build-Qt5_
`sudo apt-get install qt5-default qtbase5-dev qtscript5-dev qtmultimedia5-dev libqt5multimedia5-plugins qttools5-dev-tools   libxml2-utils`

`sudo apt-get install libglib2.0-dev libpulse-dev`

**END QLC+**

I'm still walking through the steps and will let you know if I find any more updates.

Thanks for your time!

**Comment by andyrblank** [comment]
I had issues building the latest QLC+ as it seems the required QT version is not available in Jessie. I'm closing this for now since I was unable to build and the additions here are not entirely helpful.

**Comment by magdesign** [comment]
Thanks for the info.
