### ISSUE TITLE
Shutdown button confirmation

### ISSUE THREAD

**Issue by wasabifilm** [magdesign/PocketVJ-CP-v3#98]
It would be advisable to insert a confirmation message for the shutdown button. 
Maybe even the reboot button.
This is to avoid accidentally pressing it especially when the player is inaccessible.

**Comment by magdesign** [comment]
I am more interested in which cases the player is "inaccessible" and fix this instead of
adding "omg you just pressed a button", "are you sure?", "are you really sure",  dialogues.

(I know that on the first time wifi connection the webfonts.js causes a lag of up to one minute, this is fixed in the next release currently working on).

**Comment by magdesign** [comment]
but a function to prevent bootloops when browser is reconnecting...

**Comment by wasabifilm** [comment]
sorry, but my english is not great.
When I say inaccessible I mean when the player is in an unreachable position (seven meters high or closed in a structure), and when someone presses that key (shutdown) by mistake since it is close to others, the only way to restart pocketvj is to turn off the power. But it doesn't seem like a good solution to me since there are usually other equipment on (maybe even a projector with access only from pocketvj).
Maybe there is an alternative way to start the player again?
Or can you hide that button in a more secure location?
but it's just my suggestion.

Ps: I would have two other small problems with pocketvj rtc. You prefer me to put them here or to contact you directly by email.
Thank you very much and sorry for the inconvenience

**Comment by magdesign** [comment]
Ok, the thing with the "Poweroff" is a good point.

open your issues on github, if someone else having the same question, he might find the answer here too...

**Comment by magdesign** [comment]
I will go into this, would be very useful in indeed....!
Thanks for the hint.

**Comment by magdesign** [comment]
Feature added today in CP version 3.0.3
